// GENERATED by scripts/gen-dates-ics.mjs from scripts/data/deadlines.json.
// Do not edit by hand: change the JSON, then `npm --prefix scripts run dates`.
// Raw, uncompiled, like itineraries-data.js: loaded by PAGE_MODULES on /dates.
// The resolver functions live in page-dates.jsx; this file is data only.
// The Field Guide carries a hand mirror at apps/guide/src/content/deadlines.ts,
// asserted equal to the JSON by scripts/check-deadlines.mjs.
window.DEADLINES = {
  "verified": "2026-09-05",
  "ruleYears": [
    2026,
    2027
  ],
  "items": [
    {
      "id": "halfdome-preseason",
      "title": "Half Dome preseason lottery",
      "kind": "annual",
      "start": {
        "month": 3,
        "day": 1
      },
      "end": {
        "month": 3,
        "day": 31
      },
      "time": "all day",
      "detail": "Applications open March 1 and close March 31 on Recreation.gov. Results are emailed in mid-April. $10 per application plus $10 per person if you win. About 225 day-hiker permits a day.",
      "confidence": "published",
      "source": "https://www.nps.gov/yose/planyourvisit/hdpermits.htm",
      "tag": "date-halfdome",
      "reads": [
        "half-dome-lottery"
      ]
    },
    {
      "id": "halfdome-daily",
      "title": "Half Dome daily lottery",
      "kind": "relative",
      "offsetDays": -2,
      "time": "midnight to 4 p.m.",
      "detail": "About 50 permits a day are drawn two days before the hiking date. Apply between midnight and 4 p.m. Pacific two days ahead; results arrive that evening. $10 per application plus $10 per person.",
      "confidence": "published",
      "source": "https://www.nps.gov/yose/planyourvisit/hdpermits.htm",
      "tag": "date-halfdome",
      "reads": [
        "half-dome-lottery"
      ]
    },
    {
      "id": "halfdome-cables",
      "title": "Half Dome cables season",
      "kind": "rule",
      "rule": "cables-season",
      "time": "all day",
      "detail": "The cables go up the Friday before Memorial Day and come down the day after the second Monday in October, conditions permitting. No permit is issued for a day outside the season.",
      "confidence": "published",
      "source": "https://www.nps.gov/yose/planyourvisit/hdpermits.htm",
      "tag": "date-halfdome",
      "reads": [
        "half-dome-lottery"
      ]
    },
    {
      "id": "wilderness-lottery",
      "title": "Wilderness permit lottery window",
      "kind": "relative",
      "offsetDays": -168,
      "time": "Sunday to Saturday",
      "detail": "60 percent of each trailhead's quota is drawn by lottery 24 weeks ahead: apply during the Sunday-to-Saturday week that falls 24 weeks before your start date. Results come the following Monday. $10 per application plus $5 per person.",
      "confidence": "published",
      "source": "https://www.nps.gov/yose/planyourvisit/wpres.htm",
      "tag": "date-wilderness",
      "reads": [
        "yosemite-walk-up-and-day-of-permits"
      ]
    },
    {
      "id": "wilderness-week-ahead",
      "title": "Wilderness permits: the seven-day release",
      "kind": "relative",
      "offsetDays": -7,
      "time": "7 a.m.",
      "detail": "The remaining 40 percent of each trailhead's quota is released on Recreation.gov seven days before the start date at 7 a.m. Pacific. Pickup is in person, the day before between 8 and 5 or the same day between 8 and 11.",
      "confidence": "published",
      "source": "https://www.nps.gov/yose/planyourvisit/wpres.htm",
      "tag": "date-wilderness",
      "reads": [
        "yosemite-walk-up-and-day-of-permits"
      ]
    },
    {
      "id": "camp-15th",
      "title": "Campground release: Pines, Wawona, Hodgdon Meadow",
      "kind": "release-15th",
      "monthsAhead": 5,
      "time": "7 a.m.",
      "detail": "Upper, Lower and North Pines, Wawona and Hodgdon Meadow open on Recreation.gov on the 15th of the month at 7 a.m. Pacific, five months ahead: the 15th covers arrivals from the 15th of the month five months out through the 14th of the month after. Valley sites go in minutes.",
      "confidence": "published",
      "source": "https://www.nps.gov/yose/planyourvisit/camping.htm",
      "tag": "date-camping",
      "reads": [
        "yosemite-camping-complete-guide"
      ]
    },
    {
      "id": "camp-two-weeks",
      "title": "Campground release: the two-week campgrounds",
      "kind": "relative",
      "offsetDays": -14,
      "time": "7 a.m.",
      "detail": "Bridalveil Creek, Crane Flat, Tamarack Flat, White Wolf, Yosemite Creek, Porcupine Flat and half of Tuolumne Meadows release two weeks before the arrival date at 7 a.m. Pacific.",
      "confidence": "published",
      "source": "https://www.nps.gov/yose/planyourvisit/camping.htm",
      "tag": "date-camping",
      "reads": [
        "yosemite-camping-complete-guide"
      ]
    },
    {
      "id": "camp4",
      "title": "Camp 4 release",
      "kind": "relative",
      "offsetDays": -7,
      "time": "7 a.m.",
      "detail": "Camp 4 sites release one week before the arrival date at 7 a.m. Pacific. $10 per person a night.",
      "confidence": "published",
      "source": "https://www.nps.gov/yose/planyourvisit/camping.htm",
      "tag": "date-camping",
      "reads": [
        "yosemite-camping-complete-guide"
      ]
    },
    {
      "id": "firefall",
      "title": "Horsetail Fall (Firefall) window",
      "kind": "annual",
      "start": {
        "month": 2,
        "day": 10
      },
      "end": {
        "month": 2,
        "day": 26
      },
      "time": "the last 15 minutes of light",
      "detail": "The sun lines up with Horsetail Fall in the second half of February. In 2026 the park's projected window was February 10 to 26, with no reservation required. The fall only glows if there is water in it and the western sky is clear.",
      "confidence": "typical",
      "source": "https://www.nps.gov/yose/learn/news/yosemite-national-park-prepares-for-2026-horsetail-fall-viewing.htm",
      "tag": "date-roads",
      "reads": [
        "firefall"
      ]
    },
    {
      "id": "glacier-point-open",
      "title": "Glacier Point Road typically opens",
      "kind": "annual",
      "start": {
        "month": 5,
        "day": 1
      },
      "end": {
        "month": 5,
        "day": 31
      },
      "time": "no fixed date",
      "detail": "Glacier Point Road usually opens in May once plowing is done; in 2026 it opened May 9. The park announces the date a few days ahead. Chains can still be required in the first weeks.",
      "confidence": "typical",
      "source": "https://www.nps.gov/yose/planyourvisit/glacierpointroad.htm",
      "tag": "date-roads",
      "reads": [
        "tioga-opening"
      ]
    },
    {
      "id": "tioga-open",
      "title": "Tioga Road typically opens",
      "kind": "annual",
      "start": {
        "month": 5,
        "day": 15
      },
      "end": {
        "month": 6,
        "day": 30
      },
      "time": "no fixed date",
      "detail": "Tioga Road has opened between late April and early July over the record; late May to mid-June is the usual range, and 2026 opened May 15. The park posts plowing progress weekly and announces the opening a day or two ahead.",
      "confidence": "typical",
      "source": "https://www.nps.gov/yose/planyourvisit/tiogaopen.htm",
      "tag": "date-roads",
      "reads": [
        "tioga-opening"
      ]
    },
    {
      "id": "tioga-close",
      "title": "Tioga Road typically closes",
      "kind": "annual",
      "start": {
        "month": 11,
        "day": 1
      },
      "end": {
        "month": 11,
        "day": 30
      },
      "time": "no fixed date",
      "detail": "Tioga Road closes for the season with the first storm that sticks, usually in November. Services in Tuolumne Meadows close weeks earlier: after mid-September a day up high is drive-yourself and self-supported.",
      "confidence": "typical",
      "source": "https://www.nps.gov/yose/planyourvisit/tiogaopen.htm",
      "tag": "date-roads",
      "reads": [
        "tioga-opening"
      ]
    },
    {
      "id": "tuolumne-shuttle-2026",
      "title": "Tuolumne Meadows shuttle and hikers bus end",
      "kind": "season",
      "year": 2026,
      "start": "2026-09-13",
      "end": "2026-09-13",
      "time": "last runs",
      "detail": "The Tuolumne shuttle and the Valley-to-Tuolumne hikers bus stop for 2026 on September 13. The Tuolumne store and grill close September 20. Tioga Road itself stays open until the snow closes it.",
      "confidence": "published",
      "source": "https://www.nps.gov/yose/planyourvisit/tmbus.htm",
      "tag": "date-roads",
      "reads": [
        "tioga-opening"
      ]
    },
    {
      "id": "grove-shuttle-2026",
      "title": "Mariposa Grove shuttle season",
      "kind": "season",
      "year": 2026,
      "start": "2026-05-03",
      "end": "2026-10-31",
      "time": "8 a.m. to 7 p.m. through September 23, then 8 to 5",
      "detail": "The free shuttle from the Welcome Plaza to the grove runs May 3 to October 31, 2026, with November service 8 to 3:30 and none from December to mid-April. When it is off, the Washburn Trail is 2 miles and 500 feet up to the trees.",
      "confidence": "published",
      "source": "https://www.nps.gov/yose/planyourvisit/mg.htm",
      "tag": "date-roads",
      "reads": [
        "tioga-opening"
      ]
    }
  ]
};
