import { Hono } from 'hono'
import type { Context } from 'hono'
import type { Env } from '../env'
import { constantTimeEquals } from '../lib/tokens'

// Remote photo upload: the API half of the photo-import pipeline.
//
// The repo's photo pipeline is git-based on purpose (photos deploy as
// committed static assets, with responsive variants generated by sharp and
// validated by check-guide-photos.mjs), so this Worker never writes a photo
// anywhere the site serves from. It only STAGES uploads in an R2 inbox;
// .github/workflows/photo-import.yml pulls the staged files into the
// gitignored photo-inbox/ and runs the exact same scripts/ingest-photos.mjs
// the owner runs locally (EXIF orientation + strip, downscale, mozjpeg,
// variants, credits), then opens a PR. One pipeline, two front doors.
//
// Auth is a single shared secret (PHOTO_UPLOAD_TOKEN) presented as a bearer
// token: the uploader is the site owner and the GitHub Action, nobody else.
// Every route 503s until the secret and the PHOTO_INBOX R2 binding exist, so
// deploying ahead of setup is safe.
//
// Upload rules mirror scripts/ingest-photos.mjs so a bad file fails HERE,
// where the person can fix it, instead of as a skip in the Action log:
//   - camera-default filenames (IMG_4823) are rejected: the filename becomes
//     the permanent URL key and the reference in data.js / stops.ts
//   - HEIC is rejected with the iPhone fix: the Action's sharp build cannot
//     decode HEVC (verified July 2026), so accepting one would only defer the
//     failure (the upload page's <input type=file> sidesteps this anyway:
//     iOS Safari transcodes HEIC to JPEG for web form uploads)
//   - names are slugified at upload, so inbox keys are always
//     <surface>/<slug>.<ext> and the Action's key-to-target mapping is dumb

const SURFACES = ['editorial', 'guide'] as const

const EXT_RE = /\.(jpe?g|png|webp|tiff?|dng)$/i
const HEIC_RE = /\.hei[cf]$/i
// Mirrors CAMERA_NAME_RE in scripts/ingest-photos.mjs.
const CAMERA_NAME_RE = /^(img|dsc|dscn|dscf|pxl|gopr|dji|_mg_|p\d{7}|\d+)[-_]?\d*$/i
// Stored keys are <surface>/<this>; also what the GET/DELETE params accept.
const NAME_RE = /^[a-z0-9-]{1,80}\.(jpe?g|png|webp|tiff?|dng)$/
const MAX_BYTES = 30 * 1024 * 1024

const MIME_EXT: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'image/tiff': 'tif',
}

const DEFAULT_REPO = 'goehringcory-lang/The-Talus-Field'

function slugify(basename: string): string {
  return basename
    .toLowerCase()
    .replace(/\.(jpe?g|png|webp|tiff?|dng|hei[cf])$/i, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export const photos = new Hono<{ Bindings: Env }>()

photos.use('*', async (c, next) => {
  const secret = c.env.PHOTO_UPLOAD_TOKEN
  if (!secret || !c.env.PHOTO_INBOX) {
    return c.json(
      { error: 'Photo upload is not configured (PHOTO_INBOX binding + PHOTO_UPLOAD_TOKEN secret)' },
      503,
    )
  }
  const auth = c.req.header('Authorization') ?? ''
  const presented = auth.startsWith('Bearer ') ? auth.slice(7) : ''
  if (!presented || !constantTimeEquals(presented, secret)) {
    return c.json({ error: 'Unauthorized' }, 401)
  }
  await next()
})

// POST /api/photos/upload — multipart form: file, surface (editorial|guide),
// optional name (the subject; defaults to the filename). Stages the original
// bytes untouched: EXIF (incl. any GPS fix) survives into R2 so the ingest
// can log capture coords before stripping, exactly like the local flow.
photos.post('/upload', async (c) => {
  const form = await c.req.formData().catch(() => null)
  if (!form) return c.json({ error: 'Expected a multipart form' }, 400)

  // workers-types declares FormData.get as string | null; at runtime a file
  // part is a File. Widen, then narrow on the runtime shape.
  const entry = form.get('file') as string | File | null
  if (!entry || typeof entry === 'string') {
    return c.json({ error: 'Missing file field' }, 400)
  }
  const file = entry

  const surface = String(form.get('surface') ?? '')
  if (!(SURFACES as readonly string[]).includes(surface)) {
    return c.json({ error: 'surface must be "editorial" or "guide"' }, 400)
  }

  if (file.size === 0) return c.json({ error: 'Empty file' }, 400)
  if (file.size > MAX_BYTES) {
    return c.json({ error: `File too large (max ${MAX_BYTES / 1024 / 1024} MB)` }, 413)
  }

  if (HEIC_RE.test(file.name) || /^image\/hei[cf]$/.test(file.type)) {
    return c.json(
      {
        error:
          'HEIC cannot be processed: the ingest pipeline’s image library has no HEVC decoder. ' +
          'On iPhone, set Settings > Camera > Formats > "Most Compatible" to shoot JPEG, ' +
          'or export this photo as JPEG and upload that.',
      },
      415,
    )
  }

  let ext = file.name.match(EXT_RE)?.[1]?.toLowerCase() ?? MIME_EXT[file.type]
  if (!ext) {
    return c.json({ error: 'Unsupported file type (jpg, png, webp, tiff, dng)' }, 415)
  }
  if (ext === 'jpeg') ext = 'jpg'
  if (ext === 'tiff') ext = 'tif'

  const subject = String(form.get('name') || file.name)
  const slug = slugify(subject).slice(0, 80)
  if (!slug) return c.json({ error: 'Name has no usable characters' }, 400)
  if (CAMERA_NAME_RE.test(slug)) {
    return c.json(
      {
        error:
          `"${slug}" is a camera-default name. Name the photo for its subject ` +
          '(e.g. "camp-4-morning"): the filename becomes the permanent URL key ' +
          'and the reference in stops.ts / data.js.',
      },
      400,
    )
  }

  const key = `${surface}/${slug}.${ext}`
  try {
    await c.env.PHOTO_INBOX!.put(key, await file.arrayBuffer(), {
      httpMetadata: { contentType: file.type || `image/${ext === 'jpg' ? 'jpeg' : ext}` },
      customMetadata: {
        originalName: file.name,
        uploadedAt: new Date().toISOString(),
      },
    })
  } catch (err) {
    console.error('photos: R2 put failed', { key, err })
    return c.json({ error: 'Storage write failed. Try the upload again.' }, 503)
  }

  return c.json({ key, size: file.size })
})

// GET /api/photos/pending — everything staged, for the upload page and the
// import workflow. An inbox is small by nature; one unpaginated list is fine.
photos.get('/pending', async (c) => {
  const listed = await c.env.PHOTO_INBOX!.list({ limit: 1000 })
  const items = listed.objects.map((o) => {
    const slash = o.key.indexOf('/')
    return {
      key: o.key,
      surface: slash > 0 ? o.key.slice(0, slash) : '',
      name: slash > 0 ? o.key.slice(slash + 1) : o.key,
      size: o.size,
      uploaded: o.uploaded.toISOString(),
    }
  })
  return c.json({ items })
})

// GET /api/photos/pending/:surface/:name — the staged bytes (the workflow
// downloads through here so it needs only the shared token, no Cloudflare
// credentials).
photos.get('/pending/:surface/:name', async (c) => {
  const { surface, name } = c.req.param()
  if (!(SURFACES as readonly string[]).includes(surface) || !NAME_RE.test(name)) {
    return c.json({ error: 'Bad key' }, 400)
  }
  const obj = await c.env.PHOTO_INBOX!.get(`${surface}/${name}`)
  if (!obj) return c.json({ error: 'Not found' }, 404)
  return new Response(obj.body, {
    headers: {
      'Content-Type': obj.httpMetadata?.contentType ?? 'application/octet-stream',
      'Content-Length': String(obj.size),
      'Cache-Control': 'no-store',
    },
  })
})

// DELETE /api/photos/pending/:surface/:name — the workflow removes each file
// it ingested; the upload page removes mistakes.
photos.delete('/pending/:surface/:name', async (c) => {
  const { surface, name } = c.req.param()
  if (!(SURFACES as readonly string[]).includes(surface) || !NAME_RE.test(name)) {
    return c.json({ error: 'Bad key' }, 400)
  }
  await c.env.PHOTO_INBOX!.delete(`${surface}/${name}`)
  return c.json({ deleted: `${surface}/${name}` })
})

// POST /api/photos/import — fire the repository_dispatch that starts the
// photo-import workflow. Optional: without GITHUB_DISPATCH_TOKEN the staged
// files just wait for a manual run from the repo's Actions tab (or the next
// upload session), so the message says exactly that instead of erroring
// opaquely.
photos.post('/import', async (c) => {
  const token = c.env.GITHUB_DISPATCH_TOKEN
  if (!token) {
    return c.json(
      {
        error:
          'GITHUB_DISPATCH_TOKEN is not set. Photos stay staged: run the ' +
          '"Photo import" workflow manually from the repository’s Actions tab.',
      },
      503,
    )
  }
  const repo = c.env.GITHUB_REPO || DEFAULT_REPO
  let resp: Response
  try {
    resp = await fetch(`https://api.github.com/repos/${repo}/dispatches`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'talus-field-photo-import',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ event_type: 'photo-import' }),
    })
  } catch (err) {
    console.error('photos: GitHub dispatch fetch failed', err)
    return c.json({ error: 'GitHub unreachable; photos stay staged.' }, 502)
  }
  if (resp.status === 204) return c.json({ dispatched: true })
  return c.json({ error: `GitHub dispatch failed (${resp.status})` }, 502)
})

// ---------------------------------------------------------------------------
// GET /photos — the phone upload page. Mounted at the ROOT level (like
// /widget and /tiles), not under /api/*: it serves HTML on the API origin
// itself, so the /api CORS middleware has no business running on it. The page
// carries no secrets; every request it makes presents the bearer token the
// owner pastes in once (kept in localStorage on the device).
// ---------------------------------------------------------------------------

export function photosPage(c: Context<{ Bindings: Env }>) {
  return c.html(PAGE, 200, { 'Cache-Control': 'no-store' })
}

const PAGE = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Photo inbox — The Talus Field</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 16px/1.5 -apple-system, system-ui, sans-serif; margin: 0 auto; max-width: 640px; padding: 16px; }
  h1 { font-size: 1.3rem; margin: 8px 0 4px; }
  p.note { color: #777; font-size: 0.85rem; margin: 4px 0 16px; }
  fieldset { border: 1px solid #8884; border-radius: 8px; margin: 0 0 16px; padding: 12px; }
  legend { font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #777; padding: 0 6px; }
  input[type=password], input[type=text], select { font: inherit; padding: 8px; border: 1px solid #8886; border-radius: 6px; background: transparent; color: inherit; width: 100%; box-sizing: border-box; }
  button { font: inherit; padding: 10px 14px; border: 1px solid #8886; border-radius: 8px; background: transparent; color: inherit; cursor: pointer; }
  button.primary { background: #2f5233; border-color: #2f5233; color: #fff; }
  button:disabled { opacity: 0.5; cursor: default; }
  .row { display: flex; gap: 8px; align-items: center; margin: 8px 0; }
  .row .grow { flex: 1; min-width: 0; }
  .file { border-top: 1px solid #8883; padding: 8px 0; }
  .file .meta { font-size: 0.8rem; color: #777; overflow-wrap: anywhere; }
  .warn { color: #b00; font-size: 0.85rem; }
  .ok { color: #2f7d32; font-size: 0.85rem; }
  ul { list-style: none; margin: 0; padding: 0; }
  li { border-top: 1px solid #8883; padding: 8px 0; display: flex; gap: 8px; align-items: center; }
  li .grow { flex: 1; min-width: 0; overflow-wrap: anywhere; }
  li .meta { font-size: 0.8rem; color: #777; }
  #status { margin: 12px 0; font-size: 0.9rem; min-height: 1.2em; }
</style>
</head>
<body>
<h1>Photo inbox</h1>
<p class="note">Uploads stage here, then the photo-import workflow runs the house ingest
(orientation, EXIF strip, downscale, responsive variants, credits) and opens a pull
request. Name every photo for its subject: the name becomes its permanent URL.</p>

<fieldset>
  <legend>Access</legend>
  <div class="row">
    <input type="password" id="token" class="grow" placeholder="Upload token" autocomplete="off">
    <button id="saveToken">Save</button>
  </div>
</fieldset>

<fieldset>
  <legend>Upload</legend>
  <div class="row">
    <label for="surface">Destination</label>
    <select id="surface" class="grow">
      <option value="editorial">Editorial site (img/)</option>
      <option value="guide">Field Guide (apps/guide photos)</option>
    </select>
  </div>
  <div class="row">
    <input type="file" id="files" class="grow" multiple accept="image/jpeg,image/png,image/webp,image/tiff">
  </div>
  <div id="queue"></div>
  <div class="row">
    <button id="upload" class="primary" disabled>Upload</button>
  </div>
</fieldset>

<fieldset>
  <legend>Staged, waiting for import</legend>
  <ul id="pending"></ul>
  <div class="row">
    <button id="refresh">Refresh</button>
    <button id="import" class="primary">Run import</button>
  </div>
</fieldset>

<div id="status"></div>

<script>
(function () {
  'use strict'
  var CAMERA_RE = /^(img|dsc|dscn|dscf|pxl|gopr|dji|_mg_|p\\d{7}|\\d+)[-_]?\\d*$/i
  var $ = function (id) { return document.getElementById(id) }
  var tokenInput = $('token')
  tokenInput.value = localStorage.getItem('tf.photos.token') || ''

  function status(msg, isErr) {
    var el = $('status')
    el.textContent = msg
    el.className = isErr ? 'warn' : 'ok'
  }

  function slugify(name) {
    return name.toLowerCase()
      .replace(/\\.(jpe?g|png|webp|tiff?|dng|hei[cf])$/i, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
  }

  function api(path, opts) {
    opts = opts || {}
    opts.headers = Object.assign({}, opts.headers, {
      Authorization: 'Bearer ' + tokenInput.value.trim()
    })
    return fetch('/api/photos' + path, opts).then(function (r) {
      return r.json().catch(function () { return {} }).then(function (body) {
        if (!r.ok) throw new Error(body.error || ('HTTP ' + r.status))
        return body
      })
    })
  }

  $('saveToken').onclick = function () {
    localStorage.setItem('tf.photos.token', tokenInput.value.trim())
    status('Token saved on this device.')
    refresh()
  }

  var queued = []
  $('files').onchange = function () {
    queued = []
    var box = $('queue')
    box.textContent = ''
    Array.prototype.forEach.call(this.files, function (file) {
      var slug = slugify(file.name)
      var entry = { file: file, input: null, note: null, done: false }
      var div = document.createElement('div')
      div.className = 'file'
      var meta = document.createElement('div')
      meta.className = 'meta'
      meta.textContent = file.name + ' \\u00b7 ' + (file.size / 1048576).toFixed(1) + ' MB'
      var row = document.createElement('div')
      row.className = 'row'
      var input = document.createElement('input')
      input.type = 'text'
      input.className = 'grow'
      input.placeholder = 'subject-name (e.g. camp-4-morning)'
      input.value = CAMERA_RE.test(slug) ? '' : slug
      var note = document.createElement('div')
      note.className = 'warn'
      if (CAMERA_RE.test(slug)) note.textContent = 'Camera-default filename: type a name for the subject.'
      entry.input = input
      entry.note = note
      row.appendChild(input)
      div.appendChild(meta)
      div.appendChild(row)
      div.appendChild(note)
      box.appendChild(div)
      queued.push(entry)
    })
    $('upload').disabled = queued.length === 0
  }

  $('upload').onclick = function () {
    var btn = this
    btn.disabled = true
    var surface = $('surface').value
    var chain = Promise.resolve()
    queued.forEach(function (entry) {
      chain = chain.then(function () {
        if (entry.done) return
        var name = slugify(entry.input.value)
        if (!name || CAMERA_RE.test(name)) {
          entry.note.className = 'warn'
          entry.note.textContent = 'Needs a subject name.'
          return
        }
        var form = new FormData()
        form.append('file', entry.file)
        form.append('surface', surface)
        form.append('name', name)
        entry.note.className = 'meta'
        entry.note.textContent = 'Uploading\\u2026'
        return api('/upload', { method: 'POST', body: form }).then(function (res) {
          entry.done = true
          entry.note.className = 'ok'
          entry.note.textContent = 'Staged as ' + res.key
        }, function (err) {
          entry.note.className = 'warn'
          entry.note.textContent = err.message
        })
      })
    })
    chain.then(function () {
      btn.disabled = false
      refresh()
    })
  }

  function refresh() {
    if (!tokenInput.value.trim()) return
    api('/pending').then(function (res) {
      var list = $('pending')
      list.textContent = ''
      res.items.forEach(function (item) {
        var li = document.createElement('li')
        var grow = document.createElement('div')
        grow.className = 'grow'
        grow.textContent = item.key
        var meta = document.createElement('div')
        meta.className = 'meta'
        meta.textContent = (item.size / 1048576).toFixed(1) + ' MB'
        var del = document.createElement('button')
        del.textContent = 'Remove'
        del.onclick = function () {
          api('/pending/' + item.key, { method: 'DELETE' }).then(refresh, function (err) {
            status(err.message, true)
          })
        }
        li.appendChild(grow)
        li.appendChild(meta)
        li.appendChild(del)
        list.appendChild(li)
      })
      if (!res.items.length) {
        var li = document.createElement('li')
        li.className = 'meta'
        li.textContent = 'Nothing staged.'
        list.appendChild(li)
      }
    }, function (err) { status(err.message, true) })
  }

  $('refresh').onclick = refresh
  $('import').onclick = function () {
    var btn = this
    btn.disabled = true
    api('/import', { method: 'POST' }).then(function () {
      status('Import started. The workflow will open a pull request when it finishes.')
      btn.disabled = false
    }, function (err) {
      status(err.message, true)
      btn.disabled = false
    })
  }

  refresh()
})()
</script>
</body>
</html>
`
