// Edge SEO Worker for the editorial site (the `main` entry in wrangler.jsonc,
// serving alongside the static assets). Rewrites the static index.html on the
// edge so each route ships its own <title>, meta description, canonical,
// Open Graph, Twitter, and JSON-LD structured data — without a build step.
//
// Why this exists: the editorial site is a client-rendered SPA. Without this
// rewrite, every URL serves the homepage's <head>, so non-JS crawlers (most
// AI bots, social card scrapers, Bingbot under load) see the same metadata
// for every article. The browser-side code in app.jsx still updates these
// tags after hydration; this just makes the static HTML correct from the
// first byte.
//
// History: this began life as the Cloudflare Pages Function
// functions/_middleware.js. When the site moved from Pages to a Worker with
// static assets, Pages Functions stopped executing, so the same logic now
// runs as the Worker's fetch handler. Requests that match a real file
// (/dist/*, /styles.css, /img/*, /prerender/*, …) are served by the asset
// layer and never reach this code; only SPA routes (no matching file) run it,
// which reproduces the old context.next() flow via env.ASSETS.fetch.
//
// These imports are resolved at deploy time: the JSON catalogs are baked into
// the Worker bundle, not fetched at runtime. If production is ever running an
// older build than the repo (a dashboard rollback, a stale build retry), every
// article published since that build 404s here even though the asset layer is
// serving the current sitemap that lists them. That is what the nightly
// system-checks failure of Aug 9, 2026 looked like; the fix is a redeploy of
// current main, not a repo change.

import articles from "../articles.json" with { type: "json" };
import categories from "../categories.json" with { type: "json" };
import videos from "../videos.json" with { type: "json" };
import kit from "../kit.json" with { type: "json" };
import bulletin from "../bulletin.json" with { type: "json" };
import tripPoints from "../trip-points.json" with { type: "json" };

// Slug index over the catalog. The related-reading block resolves five or six
// slugs per article request, and a linear find() per lookup would walk the
// whole catalog each time.
const articleBySlug = Object.fromEntries(articles.map((a) => [a.slug, a]));

const SITE_ORIGIN = "https://thetalusfieldjournal.com";
const SITE_NAME = "The Talus Field";
// The homepage title, and the one page title that does not end in SITE_NAME.
// It leads with the brand on purpose: the site ranked around position 16 for
// "talus field", its own name, against the geology term it is named after, and
// a title built from the bare brand plus a tagline gave Google nothing to
// distinguish the two. "The Talus Field Journal" is the form people say out
// loud, and Search Console shows them misspelling it ("tallus field",
// "talisfield"), which means the name is travelling by word of mouth and not
// landing.
//
// This string is duplicated byte for byte in index.html (<title>, og:title,
// twitter:title) and in the other of app.jsx / edge/seo.js, because `/` is
// served straight off the asset layer and never invokes the Worker, so
// index.html is what a homepage visitor actually gets. All five must move
// together; scripts/check-home-title.mjs fails the build if they drift.
const HOME_TITLE = "The Talus Field Journal — Yosemite field notes, conditions, and guides";
// 1200x630 landscape card generated by scripts/gen-responsive-images.mjs —
// matches the og:image:width/height declared in index.html.
const SITE_DEFAULT_IMAGE = `${SITE_ORIGIN}/img/og-default.jpg`;
const SITE_DEFAULT_DESC =
  "A field journal of Yosemite National Park, kept by a resident. Trails, planning notes, wildlife, and essays on the park's seasons and life.";
const AUTHOR_NAME = "Cory Goehring";
// Single author node lives in index.html (<script id="ld-person">). Article
// schema references it by @id so there is one Person entity for the whole site.
const AUTHOR_ID = `${SITE_ORIGIN}/#person-cory-goehring`;
const PUBLISHER_LOGO = `${SITE_ORIGIN}/img/talus-field-mark-square.png`;

function absoluteImage(url) {
  if (!url) return SITE_DEFAULT_IMAGE;
  if (/^https?:/i.test(url)) return url;
  return `${SITE_ORIGIN}/${url.replace(/^\//, "")}`;
}

function safeJsonForScript(obj) {
  // Defend against premature </script> termination if any string contains it.
  return JSON.stringify(obj).replace(/<\/(script)/gi, "<\\/$1");
}

// Build a BreadcrumbList from an array of [name, url] (last item omits url).
function breadcrumbLd(crumbs) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: crumbs.map(([name, url], i) => {
      const item = { "@type": "ListItem", position: i + 1, name };
      if (url) item.item = url;
      return item;
    }),
  };
}

// Build a FAQPage from an array of {q, a} pairs.
function faqLd(pairs) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: pairs.map(({ q, a }) => ({
      "@type": "Question",
      name: q,
      acceptedAnswer: { "@type": "Answer", text: a },
    })),
  };
}

// Build a TouristAttraction for a trail guide from the article's `trail` facts
// (seo-data.json). HikingTrail is not a type Google parses for rich results, so
// the hike stats ride along as additionalProperty PropertyValues. Numbers come
// from the article body; geo is emitted only when a trailhead coord is verified.
function trailLd(a, url) {
  const t = a.trail;
  const props = [];
  if (t.distance) props.push({ "@type": "PropertyValue", name: "Distance", value: t.distance });
  if (t.elevationGain) props.push({ "@type": "PropertyValue", name: "Elevation gain", value: t.elevationGain });
  if (t.difficulty) props.push({ "@type": "PropertyValue", name: "Difficulty", value: t.difficulty });
  const ld = {
    "@context": "https://schema.org",
    "@type": "TouristAttraction",
    name: t.name || a.title,
    description: a.seoDek || a.dek,
    url,
    touristType: "Hikers",
    isAccessibleForFree: true,
    containedInPlace: { "@type": "Place", name: "Yosemite National Park" },
  };
  if (props.length) ld.additionalProperty = props;
  if (t.geo && typeof t.geo.lat === "number" && typeof t.geo.lng === "number") {
    ld.geo = { "@type": "GeoCoordinates", latitude: t.geo.lat, longitude: t.geo.lng };
  }
  return ld;
}

// ---------------------------------------------------------------------------
// Crawler-visible prose for non-article routes. Articles get their committed
// /prerender/<slug>.html fragment; hub/section pages get these fragments,
// built from the same JSON mirrors this Worker already imports (so the lists
// stay fresh with the catalog) plus short hand-written intros. Injected into
// #root exactly like article prose so non-JS crawlers (Bing, AI answer
// engines, social scrapers) see route-specific headings and body text instead
// of the homepage-generic <noscript>. Each fragment carries its own <h1>; the
// static #seo-static-h1 is removed whenever a fragment is injected and
// rewritten to the route title otherwise.
// ---------------------------------------------------------------------------
function articleLinkList(list) {
  return `<ul>${list
    .map((a) => `<li><a href="/articles/${a.slug}">${escapeHtmlText(a.title)}</a>: ${escapeHtmlText(a.seoDek || a.dek)}</li>`)
    .join("")}</ul>`;
}

function hubProse(h1, intro, extraHtml) {
  return `<h1>${escapeHtmlText(h1)}</h1><p>${escapeHtmlText(intro)}</p>${extraHtml || ""}`;
}

// Curated onward links for an article, appended to its injected prose.
//
// The prerendered fragments carry an article's in-body links, but nothing
// carried the related rail: that was React-only, so the crawler-visible HTML
// ended at the last paragraph. Reading the `related` field out of articles.json
// (resolved by data.js's own relatedFor, so this cannot disagree with the rail
// a reader sees) puts five or six more real links on every article page.
//
// This is appended INSIDE the #prerender-prose block on purpose. app.jsx
// removes exactly that node at boot; a sibling would survive the removal and
// flash beneath the React-rendered page until something else cleaned it up.
function relatedBlock(slug) {
  const a = articleBySlug[slug];
  const list = (a && a.related) || [];
  const items = list.map((s) => articleBySlug[s]).filter(Boolean);
  if (!items.length) return "";
  return `<nav aria-label="Related reading"><h2>Related reading</h2>${articleLinkList(items)}</nav>`;
}

// Hand-maintained mirror of itineraries-data.js: drives both the TouristTrip
// ItemList and the /itineraries crawler prose. Update alongside that file.
const ITINERARY_TRIPS = [
  {
    id: "1day",
    name: "One day in the Valley",
    description:
      "The Valley floor, west to east, morning to dinner. Arrive early, park once if you can, and let the day move at walking pace between the famous walls.",
  },
  {
    id: "2day",
    name: "The Valley, then the rim",
    description:
      "Day one on the Valley floor. Day two up Glacier Point Road, stopping in trailhead order, for the views that look back down on everything you walked the day before.",
  },
  {
    id: "3day",
    name: "Valley, rim, and high country",
    description:
      "The two-day plan, then a third day on Tioga Road, west to east toward the pass. The high country is a different park: granite domes, subalpine lakes, and half the crowd.",
  },
  {
    id: "halfday",
    name: "Arriving at two",
    description:
      "The honest plan for a late arrival: skip the trailheads, take the meadows and the river, and end at the pizza deck while the light is still on the walls.",
  },
];

// Crawler prose for the static hub routes, keyed by path. Values are thunks so
// only the matched route's fragment is built per request. Short hand-written
// intros in the house voice; lists are generated from the imported JSON
// mirrors so they never go stale against the catalog.
const HUB_PROSE = {
  "/articles": () =>
    hubProse(
      "Articles",
      "Every entry in the journal, newest first: Yosemite trip planning, trails and hikes, wildlife and nature, and seasonal guides, written from inside the park.",
      articleLinkList(articles)
    ),
  "/planning": () =>
    hubProse(
      "The Yosemite Planning Guide",
      "Planning advice from inside the park, checked on foot: entrances and getting here, gateway towns, permits, Half Dome, accessibility, smoke season, and the seasonal calendar. The planning archive, curated:",
      // The page renders PLANNING_SERIES members from every section, so the
      // crawler prose lists the same curation (planningSeries rides in from
      // articles.json).
      articleLinkList(articles.filter((a) => a.cat === "planning" || a.planningSeries))
    ),
  "/checklist": () =>
    hubProse(
      "The Yosemite First-Week Checklist",
      "A printable single-page checklist for the first week of planning a Yosemite trip: when to come, what to book and in what order, what to pack, which gateway to base in, and the non-negotiables. Free, no signup required."
    ) +
    `<p>The reasoning behind each line item lives in <a href="/planning">the Planning Guide</a>; the packing details live in <a href="/kit">the kit lists</a>.</p>`,
  "/kit": () =>
    hubProse(
      "What to pack",
      "Three packing checklists for a Yosemite trip: a day pack, what an overnight adds to it, and the full car load."
    ) +
    kit.lists
      .map(
        (list) =>
          `<h2>${escapeHtmlText(list.title)}</h2><p>${escapeHtmlText(list.summary)}</p><ul>${list.items
            .map((it) => `<li>${escapeHtmlText(it.name)}${it.note ? `: ${escapeHtmlText(it.note)}` : ""}</li>`)
            .join("")}</ul>`
      )
      .join(""),
  "/films": () =>
    hubProse(
      "Moving Pictures: the Yosemite Nature Notes film archive",
      "The complete Yosemite Nature Notes series from the National Park Service, grouped by subject. Public domain, free to watch, most under ten minutes."
    ) +
    `<ul>${videos.map((ep) => `<li>${escapeHtmlText(ep.title)}: ${escapeHtmlText(ep.dek)}</li>`).join("")}</ul>`,
  "/itineraries": () =>
    hubProse(
      "Yosemite itineraries: day plans on the map",
      "Curated Yosemite itineraries for one, two, or three days, plus a half-day plan for late arrivals. Each opens as a ready-made trip on the interactive trip planner map."
    ) +
    ITINERARY_TRIPS.map((t) => `<h2>${escapeHtmlText(t.name)}</h2><p>${escapeHtmlText(t.description)}</p>`).join("") +
    `<p>Open any plan on <a href="/map">the trip planner map</a>, or check <a href="/conditions">current conditions</a> before you drive in.</p>`,
  "/map": () =>
    hubProse(
      "The Yosemite trip planner map",
      "An interactive map of Yosemite National Park: vistas, trailheads, parking turnouts, picnic spots, and places to eat, each pin curated and written by a resident of the park. Filter pins by category, search by name, and assemble stops into a trip you can share by link, email to yourself, or open in Google Maps for driving directions. The full map opens with a free newsletter signup."
    ) +
    `<p>Prefer a ready-made plan? Start from <a href="/itineraries">the curated itineraries</a>. Planning the drive in? Check <a href="/conditions">webcams, entrance waits, and weather</a>.</p>`,
  // /search is noindex (see the `known` entry below): a results page is thin,
  // duplicative content and Google says as much. The prose is here for the
  // "follow" half — it is a plain table of contents, so a crawler that lands
  // on the page still finds its way into the sections.
  "/search": () =>
    hubProse(
      "Search The Talus Field",
      "Search every article, section, and page in The Talus Field: Yosemite planning notes, trail reports, wildlife and natural history, and seasonal guides."
    ) +
    `<p>Browse instead: <a href="/explore">the site index</a>, <a href="/articles">all articles</a>, <a href="/section/planning">planning</a>, <a href="/section/trails">trails and hikes</a>, <a href="/section/wildlife">wildlife and nature</a>, <a href="/section/seasonal">seasonal guides</a>, or <a href="/now">The Park Bulletin</a>.</p>`,
  // /explore is the human table of contents. Its whole value is the link graph,
  // so the crawler prose IS the link list — every reader-facing destination on
  // the site, in one hop from one indexable page.
  "/explore": () =>
    hubProse(
      "Everything on The Talus Field",
      "The site index: every destination in this Yosemite field journal, with a line on what each one is for."
    ) +
    `<h2>Read</h2>` +
    `<p><a href="/articles">All articles</a> · <a href="/section/planning">Planning</a> · <a href="/section/trails">Trails and hikes</a> · <a href="/section/wildlife">Wildlife and nature</a> · <a href="/section/seasonal">Seasonal guides</a> · <a href="/now">The Park Bulletin</a> · <a href="/films">Films</a> · <a href="/archive/">The Nature Notes archive</a> · <a href="/search">Search</a></p>` +
    `<h2>Plan a trip</h2>` +
    `<p><a href="/planning">The Yosemite Planning Guide</a> · <a href="/map">The Map</a> · <a href="/itineraries">Itineraries</a> · <a href="/stay">Where to stay</a> · <a href="/conditions">Conditions</a> · <a href="/checklist">The first-week checklist</a> · <a href="/kit">The Kit</a> · <a href="/consult">Trip consults</a></p>` +
    `<h2>Dated events</h2>` +
    `<p><a href="/firefall">Firefall</a> · <a href="/tioga-opening">The Tioga Road opening</a> · <a href="/half-dome-lottery">The Half Dome lottery</a></p>` +
    `<h2>The Field Guide</h2>` +
    `<p><a href="/guide">The Field Guide</a> · <a href="/partners">Group codes</a></p>` +
    `<h2>The journal</h2>` +
    `<p><a href="/about">About the journal</a> · <a href="/newsletter">Sunday Field Notes</a> · <a href="/contact">Contact</a> · <a href="/places">The Directory</a> · <a href="/advertise">Advertise</a> · <a href="/widget">The conditions widget</a> · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/affiliate">Affiliate disclosure</a></p>`,
  "/conditions": () =>
    hubProse(
      "Yosemite conditions: webcams, waits, and weather",
      "The morning-of page: live Yosemite webcams, current entrance wait times, and elevation-aware National Weather Service point forecasts for the Valley, the rim, and the high country, all on one page. Bookmark it and check it the morning you drive in."
    ) +
    `<p>For what the conditions mean for a plan, see <a href="/itineraries">the itineraries</a> and <a href="/planning">the Planning Guide</a>.</p>`,
  "/now": () => {
    // The current edition ships to non-JS crawlers as prose: this page's value
    // to search is its freshness, and bulletin.json is imported at deploy time
    // so every per-edition merge re-deploys the Worker with the new board.
    const ed = bulletin.edition || {};
    const parts = [
      hubProse(
        "The Park Bulletin",
        `Everything happening in Yosemite right now on one scannable page, condensed from the park's Yosemite Guide for ${ed.label || "the current edition"}: closures, roads, free ranger programs, dated events, trail status, hours, and phone numbers.`
      ),
    ];
    if (ed.lede) parts.push(`<p>${escapeHtmlText(ed.lede)}</p>`);
    if (Array.isArray(bulletin.alerts) && bulletin.alerts.length) {
      parts.push(
        // An alert is a plain string or { icon, text }; the icon is a
        // wayfinding mark on the rendered page and carries nothing a crawler
        // needs, so only the text crosses over.
        `<h2>Changed this edition</h2><ul>${bulletin.alerts
          .map((a) => `<li>${escapeHtmlText(typeof a === "string" ? a : (a && a.text) || "")}</li>`)
          .join("")}</ul>`
      );
    }
    if (Array.isArray(bulletin.areas) && bulletin.areas.length) {
      parts.push(
        `<h2>Roads and areas</h2><ul>${bulletin.areas
          .map((a) => `<li>${escapeHtmlText(a.name)} (${escapeHtmlText(a.chip)}): ${escapeHtmlText(a.note)}</li>`)
          .join("")}</ul>`
      );
    }
    if (Array.isArray(bulletin.valleyDay) && bulletin.valleyDay.length) {
      parts.push(
        `<h2>The Valley, by the clock</h2><ul>${bulletin.valleyDay
          .map((p) => {
            // The Guide's per-program symbols, carried into the crawler prose
            // for the same reason they are on the page: they decide whether a
            // reader can attend. True-only, so nothing renders when unmarked.
            const marks = [p.allAges ? "all ages" : null, p.access ? "wheelchair accessible" : null].filter(Boolean);
            const suffix = marks.length ? `, ${marks.join(", ")}` : "";
            return `<li>${escapeHtmlText(p.time)}: ${escapeHtmlText(p.title)} (${escapeHtmlText(p.days)}${escapeHtmlText(suffix)})</li>`;
          })
          .join("")}</ul>`
      );
    }
    if (Array.isArray(bulletin.events) && bulletin.events.length) {
      parts.push(
        `<h2>On the calendar this edition</h2><ul>${bulletin.events
          .map((ev) => `<li>${escapeHtmlText(ev.dates)}: ${escapeHtmlText(ev.title)}, ${escapeHtmlText(ev.where)}</li>`)
          .join("")}</ul>`
      );
    }
    if (Array.isArray(bulletin.trails) && bulletin.trails.length) {
      parts.push(
        `<h2>Trails right now</h2><ul>${bulletin.trails
          .map((t) => `<li>${escapeHtmlText(t.name)} (${escapeHtmlText(t.chip)}): ${escapeHtmlText(t.note)}</li>`)
          .join("")}</ul>`
      );
    }
    parts.push(
      `<p>Live sources on <a href="/conditions">the conditions page</a>; the Sunday letter carries what changed on this board by email.</p>`
    );
    return parts.join("");
  },
  "/guide": () =>
    hubProse(
      "The Field Guide",
      "An offline web app for Yosemite, written and field-checked by a naturalist who lives in the park. 81 entries across the Valley, Glacier Point and Mariposa Grove, Tuolumne, and Hetch Hetchy, each with a tappable GPS coordinate and an honest time budget, the flagship stops with a swap for when the lot is full. All 57 in-park day hikes with GPS tracks and elevation profiles. The ranger and partner program schedule on your dates. A trip planner that builds each day in driving order with real drive-time buffers, then saves the plan to your calendar as a file. One download of about 70 MB carries the whole guide, the photos on file and a topographic park map, so everything keeps working when cell service dies."
    ) +
    `<p>The guide is on sale now: $3.99 once for 18 months of access on every personal device, no subscription, refunded in full within 30 days if it does not work as described. The journal's free tools cover a lot on their own: <a href="/map">the trip planner map</a>, <a href="/itineraries">itineraries</a>, and <a href="/checklist">the first-week checklist</a>.</p>`,
  "/about": () =>
    hubProse(
      "About The Talus Field",
      "The Talus Field is an independent field journal of Yosemite National Park, written by Cory Goehring, a naturalist who lives in El Portal and has worked in and around the park for twenty seasons. Articles are checked on foot; gear is recommended only after real miles; nothing here is sponsored content."
    ),
  // The five entries below were one sentence each until August 2026. A crawler
  // running no JavaScript saw an <h1> and a single line, which is the shape of
  // an error page, and Search Console was reporting three soft 404s: URLs that
  // return 200 carrying what Google reads as "not found". Each now states what
  // the page actually holds, drawn from the page's own copy so the two cannot
  // drift into saying different things.
  "/places": () =>
    hubProse(
      "The Directory",
      "A small, curated directory of Yosemite-area lodging, outfitters, guides, and tour operators, drawn from twenty seasons in and around the park. Listings are added slowly and on merit: the standard is whether the operator would be recommended to a friend, not whether they paid.",
      "<p>Five categories are open. <strong>Lodging</strong>: lodges, inns and small hotels inside the park or within an hour of a gate, family-run preferred. <strong>Guides and instruction</strong>: climbing schools, hiking guides and naturalist programs that are permitted, insured, and not running on charisma alone. <strong>Outfitters</strong>: gear rental and resupply for travelers who flew in or forgot the one important thing. <strong>Tours and transportation</strong>: drivers, shuttles and scheduled tours moving readers between the Valley, the high country and the gateway towns. <strong>Vacation rentals</strong>: independently operated houses and cabins in the gateway towns, owners who answer their own phone.</p>" +
        "<p>The directory covers three areas of the park: Yosemite Valley, Glacier Point and Mariposa Grove on the south rim, and Tuolumne Meadows above 8,000 feet, which is summer only. Operators can read the terms on the listing page; every paid placement is labeled as one.</p>"
    ),
  "/newsletter": () =>
    hubProse(
      "Sunday Field Notes",
      "A short note on Yosemite most Sundays, when there is something to say: conditions, openings, what the park is doing right now. Subscribing also unlocks the interactive trip planner map. Free.",
      "<p>The letter goes out when there is news worth sending rather than on a fixed schedule, so a quiet fortnight in the park means a quiet inbox. Typical subjects: which roads have opened or closed, what the waterfalls are doing, when a permit window falls, and the seasonal things that are easy to miss by a week, from the February light on Horsetail Fall to the first snow on Tioga Road.</p>" +
        "<p>One signup also opens the trip planner map, which carries every vista, trailhead, parking turnout and meal worth stopping for, and lets a reader build a trip from the pins and share it as a link. No cost, and the archive of past letters is open.</p>"
    ),
  "/contact": () =>
    hubProse(
      "Contact",
      "Send a note to the editor: trip questions, corrections, press, or anything else. Replies come from a real person in El Portal.",
      "<p>Corrections are welcome and get published. Everything here is written by one naturalist who lives at the park's western edge, and readers on the ground regularly know something the article does not: a closed trail, a changed shuttle stop, a restaurant that stopped serving lunch. Press and partnership enquiries reach the same inbox, as do questions about listing a business in the directory.</p>"
    ),
  "/advertise": () =>
    hubProse(
      "List your business",
      "How to list a Yosemite-area lodge, inn, guide service, or outfitter in The Talus Field directory, and what the listing includes.",
      "<p>The Talus Field is read by people actively planning a Yosemite trip, the audience that is about to book lodging, hire a guide or buy a tour. A standard listing carries the business name, its area, a short editorial blurb, a direct outbound link to the booking page, and inclusion in the relevant category, for twelve months and renewable. A featured listing adds a photo, an extended description and priority position within its category.</p>" +
        "<p>What the directory will not do is listed as plainly: no businesses the editor would talk a friend out of using, no unlabeled sponsorship (every paid placement is marked), no payment overriding the editorial tone of a blurb, and no placements from operators with active permit or safety violations. Rates are quoted on enquiry.</p>"
    ),
  "/widget": () =>
    hubProse(
      "The Yosemite conditions widget",
      "A free embeddable box for Yosemite-area websites: live entrance waits from the National Park Service feed and the three-day Valley forecast from the National Weather Service, rendered by a single script tag with a credit link back to The Talus Field's conditions page. Built for gateway hotels, rental hosts, and tour operators."
    ) +
    `<p>See it live and copy the snippet on this page. The full conditions layer is at <a href="/conditions">/conditions</a>.</p>` +
    `<p>Lodging operators who want the guide itself for their guests: <a href="/partners">group codes</a>.</p>`,
  "/partners": () =>
    hubProse(
      "Group codes: the Field Guide for your guests",
      "Yosemite-area hotels, inns, vacation rental hosts, and property managers can buy The Talus Field Guide in packs and give a code to every booking. One code is one guest's full access for 18 months on every device they own: 44 stops with GPS and time budgets, all 57 in-park day hikes, the 37-entry Secret Guide, a day-by-day trip planner, park programs on their dates, and an offline topographic map of the park. Nothing to install, host, or support on the property's side."
    ) +
    `<p>Pricing is quoted per property rather than published. Billed by invoice, no revenue share, no exclusivity. The first properties are onboarded by hand.</p>` +
    `<p>The public product page is <a href="/guide">the Field Guide</a>. The free conditions embed for your own site is at <a href="/widget">/widget</a>, and directory listings are at <a href="/advertise">/advertise</a>.</p>`,
  "/consult": () =>
    hubProse(
      "Field consult: thirty minutes on your Yosemite plan",
      "A one-on-one planning session with a naturalist who lives in Yosemite: dates, group, and constraints turned into a plan that fits the park as it will actually be that week. Thirty minutes by call, or the same session asynchronously as a written plan. A few slots a month; when they are gone, they are gone."
    ) +
    `<p>Most planning questions are answered free in <a href="/planning">the Planning Guide</a>, <a href="/itineraries">the itineraries</a>, and <a href="/map">the trip planner map</a>; the consult is for plans with real constraints.</p>`,
  "/stay": () =>
    hubProse(
      "Where to Stay in Yosemite",
      "Every place to sleep in and around the park, sorted by what it is and who it fits. Inside the boundary there is one operator: every hotel, lodge, and tent cabin is run by a single park concessioner and books through travelyosemite.com, with reservations opening 366 days ahead and peak Valley dates gone in minutes. Outside the boundary there is a real market across five gateway towns whose drive times differ by more than an hour."
    ) +
    `<p>Inside the park: <strong>Yosemite Valley Lodge</strong>, the correct answer for most first-time visitors, across the road from Lower Yosemite Fall. <strong>The Ahwahnee</strong>, a 1927 National Historic Landmark, for the occasion that justifies it. <strong>Curry Village</strong>, canvas tent cabins at the base of Glacier Point since 1899 and the cheapest roofed beds in the Valley. <strong>Housekeeping Camp</strong>, three-walled river units where you can cook over a fire. <strong>White Wolf Lodge</strong> at 8,000 feet and <strong>Tuolumne Meadows Lodge</strong> at 8,700, both summer-only tent cabins for high-country trips. The historic <strong>Wawona Hotel</strong> has been closed for renovation since December 2024.</p>` +
    `<p>The gateway towns, by drive time to Yosemite Valley: <strong>El Portal</strong> (25 to 35 minutes, Highway 140), <strong>Mariposa</strong> (45 to 60 minutes, the most full-service and the safest first-timer's pick), <strong>Groveland</strong> (65 to 80 minutes on Highway 120, the character pick), <strong>Oakhurst</strong> (75 to 90 minutes on Highway 41, best for Wawona and the Mariposa Grove), and <strong>Lee Vining</strong> (90 minutes and only while Tioga Pass is open, the east-side base for the high country and Mono Lake).</p>` +
    `<p>The longer versions: <a href="/articles/where-to-stay-in-yosemite">the in-park lodging guide</a>, <a href="/articles/yosemite-gateway-towns-compared">the gateway towns compared</a>, <a href="/articles/yosemite-camping-complete-guide">the complete camping guide</a>, and <a href="/articles/yosemite-trip-cost-budget-2026">what a Yosemite trip costs</a>.</p>`,
  "/firefall": () =>
    hubProse(
      "The Yosemite Firefall",
      "For roughly two weeks in mid-to-late February, sunset light can turn Horsetail Fall into a glowing orange ribbon on El Capitan. Three conditions must hold at once: water in the fall from recent rain or snowmelt, a clear western horizon at sunset, and the February sun angle. The glow builds for a few minutes, peaks near sunset, and is finished about ten minutes later."
    ) +
    `<p>The classic viewing zone is Northside Drive near the El Capitan Picnic Area; parking rules and any reservation requirement change annually, so check the NPS Horsetail Fall page before committing.</p>` +
    `<p>The full guide: <a href="/articles/horsetail-fall-firefall">the complete firefall article</a>. Live water and weather: <a href="/conditions">the conditions page</a>.</p>`,
  "/tioga-opening": () =>
    hubProse(
      "The Tioga Road Opening",
      "Every spring, plow crews cut Highway 120 out of the snowpack and the highest road in Yosemite comes back. There is no fixed opening date: the long-term average is the end of May, light years have opened in mid-May, heavy years run into June or later, and the park announces the date only days ahead. In week one the road is open but the services are not: no potable water, nothing to buy, no gas between Crane Flat and Lee Vining, and the famous high trails still under snow. The early season rewards drivers, photographers, and modest walkers."
    ) +
    `<p>The reliable early stops are Olmsted Point, Tenaya Lake's east beach, the Tuolumne Meadows pullouts, Pothole Dome, and Soda Springs. The full day-by-day version: <a href="/articles/tioga-road-opening-weekend-2026">the opening-weekend field guide</a>. Current status: <a href="/now">the Park Bulletin</a> and the NPS Tioga Road page.</p>`,
  "/webcams": () =>
    hubProse(
      "Yosemite Webcams",
      "The live cameras worth checking before you drive in. Four Yosemite Conservancy cameras run on this page: Half Dome from Ahwahnee Meadow looking east, Upper Yosemite Fall from the Valley floor, El Capitan and the western Valley from Turtleback Dome, and Wawona at the park's south end. All four are still-image cameras that refresh on the order of minutes rather than video streams.",
      "<p>How to read them: check two rather than one, because a single camera describes one wall while Half Dome plus El Capitan tells you whether the whole Valley is clear, socked in or hazy. Elevation matters more than the pictures suggest, since the Valley floor is at 4,000 feet and Tuolumne Meadows at 8,600, so a clear Valley camera says nothing about whether it is snowing on Tioga Road. And a dry waterfall on the Yosemite Falls camera in August is the season, not a broken camera.</p>" +
        "<p>There is no Conservancy camera at Tuolumne Meadows or Tioga Pass, which is the most requested view the park does not have. Full camera list: <a href=\"https://yosemite.org/webcams/\">Yosemite Conservancy</a>. Road status and closures: <a href=\"/now\">the Park Bulletin</a>. Forecasts and live entrance waits: <a href=\"/conditions\">the conditions page</a>. Which waterfalls are running on your dates: <a href=\"/articles/yosemite-waterfalls-guide\">the flow-by-month table</a>.</p>"
    ),
  "/distances": () =>
    hubProse(
      "Yosemite Drive Times",
      "How far Yosemite Valley is from each gateway town, in one table. El Portal is about 14 miles and 25 to 35 minutes on Highway 140; Mariposa about 45 miles and 45 to 60 minutes on the same road; Groveland about 41 miles and 65 to 80 minutes on Highway 120, where chain controls are common in winter; Oakhurst about 50 miles and 75 to 90 minutes on Highway 41; and Lee Vining about 75 miles and 90 minutes minimum over Tioga Pass, only while the pass is open.",
      "<p>Other legs the Valley table does not answer: Oakhurst to the South Entrance is about 14 miles and 20 to 25 minutes, with the Mariposa Grove welcome plaza immediately inside the gate and Wawona six miles further on; Groveland to the Big Oak Flat Entrance is about 24 miles and 30 to 40 minutes on a winding road; Lee Vining to Tuolumne Meadows is about 20 miles and 30 minutes while Tioga Pass is open. Oakhurst is the longest drive to the Valley of the four year-round towns and the shortest to the sequoias by a wide margin.</p>" +
        "<p>Times are to the west end of Yosemite Valley in ordinary conditions; add 15 to 20 minutes for Curry Village at the east end, and more for summer afternoons. Season changes the answer more than distance does, and entrance queues on a peak morning can add half an hour no mileage predicts. Full comparison: <a href=\"/articles/yosemite-gateway-towns-compared\">the gateway towns guide</a>. Live waits: <a href=\"/conditions\">the conditions page</a>.</p>"
    ),
  "/half-dome-lottery": () =>
    hubProse(
      "The Half Dome Lottery",
      "There are two Half Dome permit lotteries, not one. The preseason lottery takes applications on Recreation.gov through March with results in mid-April; the daily lottery runs every day the cables are up, taken two days before the hike date. In the 2024 season the National Park Service recorded 35,289 preseason applications at a 22% success rate and 35,561 daily-lottery applications at 19%, with weekday odds in the daily lottery running 22% against 14% on weekends. Late-season weekdays are the best draw of the year. Strategy: use all seven date choices, front-load unpopular dates, avoid Saturday, enter both lotteries, and plan the hike mid-trip so the daily lottery gets several independent draws."
    ) +
    `<p>The cables are up from about the Friday before Memorial Day to the day after the second Monday in October. A permit is required past the base of the subdome, checked against photo ID, with 300 hikers a day allowed through: roughly 225 day hikers from these lotteries and 75 backpackers on wilderness permits. Going without one violates 36 CFR 1.6 and carries a fine of up to $5,000.</p>` +
    `<p>Whether the hike itself is the right goal: <a href="/articles/so-you-want-to-hike-half-dome">So You Want to Hike Half Dome</a>, which makes the case for Clouds Rest. Every other permit the park runs: <a href="/articles/yosemite-wilderness-permits-guide">the wilderness permits guide</a> and <a href="/articles/yosemite-walk-up-and-day-of-permits">walk-up and day-of permits</a>.</p>`,
  // The three legal pages are indexable but render nothing for non-JS
  // crawlers without a prose entry — a one-paragraph summary each keeps them
  // from reading as empty (thin) pages. Facts follow the published page copy
  // in page-legal.jsx; when that copy changes materially, change these.
  "/privacy": () =>
    hubProse(
      "Privacy Policy",
      "What The Talus Field collects when you visit the site, subscribe to the newsletter, or use the Field Guide app, how it is used, and the choices you have, written to comply with the GDPR and the CCPA. The Talus Field is an independent publication operated by Cory Goehring, reachable at cory@thetalusfieldjournal.com."
    ),
  "/terms": () =>
    hubProse(
      "Terms of Service",
      "The terms that govern thetalusfieldjournal.com and the Field Guide app. The articles and the trip-planner map are free to browse. The Field Guide is a one-time purchase, not a subscription: 18 months of access on any device you sign in to, payment processed by Stripe, and a full refund within 30 days if it does not work as described."
    ),
  "/affiliate": () =>
    hubProse(
      "Affiliate Disclosure",
      "Some links on this site are affiliate links: The Talus Field participates in Patagonia's program through Impact and the Expedia Group Travel Creator Program through Partnerize, which powers the lodging availability links. A booking through one earns a small commission at no extra cost. The governing rule: no program's catalog shapes a recommendation, and the best option stays the top recommendation, linkless, if it has no program."
    ),
};

// Shared-trip unfurls: /map?trip=id1,id2 links travel through texts and group
// chats, and the card is the click. Overrides title/description/og:image with
// the trip's stop count and first stop names (validated against the
// trip-points.json mirror; unknown ids are dropped, an all-invalid trip falls
// back to the generic /map card). `ogUrl` carries the full shared URL so
// scrapers unfurl the specific trip, while canonical stays a clean /map and
// search consolidates there. Cards are pre-generated by scripts/gen-og-cards.mjs.
const TRIP_OG_CARD_MAX = 20;
function applyTripSeo(seo, searchParams) {
  const trip = searchParams && searchParams.get("trip");
  if (!trip) return;
  const ids = [...new Set(trip.split(",").map((s) => s.trim()))].filter((id) =>
    Object.prototype.hasOwnProperty.call(tripPoints, id)
  );
  if (!ids.length) return;
  const n = ids.length;
  const names = ids.slice(0, 2).map((id) => tripPoints[id]);
  const rest = n - names.length;
  const stopList = rest > 0 ? `${names.join(", ")}, and ${rest} more` : names.join(", ");
  seo.title = `A ${n}-stop Yosemite trip — ${SITE_NAME}`;
  seo.description = `${stopList}, in drive order. A shared trip on the Talus Field planner map, curated by a resident of the park. Open it to see the route.`;
  seo.image = `${SITE_ORIGIN}/img/og/trip-${Math.min(n, TRIP_OG_CARD_MAX)}.jpg`;
  seo.ogUrl = `${SITE_ORIGIN}/map?trip=${ids.join(",")}`;
}

function seoForPath(pathname, searchParams) {
  const path = pathname.replace(/\/+$/, "") || "/";

  const articleMatch = path.match(/^\/articles\/([a-z0-9-]+)$/i);
  if (articleMatch) {
    const a = articles.find((x) => x.slug === articleMatch[1]);
    if (!a) return null;
    const cat = categories.find((c) => c.slug === a.cat);
    // Prefer the slug-named responsive variant (a few hundred KB, under the
    // social scrapers' size caps) over the multi-MB source JPEG.
    const image = absoluteImage(a.ogImage ? a.ogImage.url : a.image);
    const url = `${SITE_ORIGIN}/articles/${a.slug}`;
    // Prefer the short SEO description when authored, otherwise fall back to
    // the visible dek. Keeps Bing/Google snippets under the 160-char cutoff.
    const desc = a.seoDek || a.dek;
    return {
      title: `${a.title} — ${SITE_NAME}`,
      description: desc,
      canonical: url,
      ogType: "article",
      // Prerender hooks (see onRequest): the slug locates the committed
      // /prerender/<slug>.html prose fragment, the title heads the injected
      // block, and the hero path drives the per-route LCP preload (C12).
      prerenderSlug: a.slug,
      articleTitle: a.title,
      heroImagePath: a.image || null,
      image,
      imageWidth: a.ogImage ? a.ogImage.width : null,
      imageHeight: a.ogImage ? a.ogImage.height : null,
      imageAlt: a.placeholder || a.title,
      articleOg: {
        publishedTime: a.isoDate || null,
        modifiedTime: a.isoModified || a.isoDate || null,
        author: AUTHOR_NAME,
        section: cat ? cat.label : null,
      },
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "Article",
        headline: a.title,
        description: desc,
        // ImageObject with real pixel dimensions when the og variant
        // resolved (the same numbers og:image:width/height carry); a bare
        // URL otherwise.
        image: a.ogImage
          ? [{ "@type": "ImageObject", url: image, width: a.ogImage.width, height: a.ogImage.height }]
          : [image],
        datePublished: a.isoDate || a.date,
        dateModified: a.isoModified || a.isoDate || a.date,
        articleSection: cat ? cat.label : undefined,
        wordCount: typeof a.wordCount === "number" ? a.wordCount : undefined,
        keywords: Array.isArray(a.keywords) && a.keywords.length ? a.keywords : undefined,
        author: { "@id": AUTHOR_ID },
        publisher: {
          "@type": "Organization",
          name: SITE_NAME,
          logo: { "@type": "ImageObject", url: PUBLISHER_LOGO },
        },
        mainEntityOfPage: { "@type": "WebPage", "@id": url },
        isAccessibleForFree: true,
        inLanguage: "en-US",
      },
      breadcrumb: breadcrumbLd([
        ["Home", `${SITE_ORIGIN}/`],
        cat ? [cat.label, `${SITE_ORIGIN}/section/${cat.slug}`] : null,
        [a.title, null],
      ].filter(Boolean)),
      faq: Array.isArray(a.faq) && a.faq.length ? faqLd(a.faq) : null,
      trail: a.trail ? trailLd(a, url) : null,
    };
  }

  const sectionMatch = path.match(/^\/section\/([a-z0-9-]+)$/i);
  if (sectionMatch) {
    const cat = categories.find((c) => c.slug === sectionMatch[1]);
    if (!cat) return null;
    const items = articles.filter((a) => a.cat === cat.slug);
    const url = `${SITE_ORIGIN}/section/${cat.slug}`;
    return {
      title: `${cat.label} — ${SITE_NAME}`,
      description: `${cat.blurb} ${items.length} entries from The Talus Field's Yosemite field journal.`,
      canonical: url,
      ogType: "website",
      image: SITE_DEFAULT_IMAGE,
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        name: `${cat.label} — ${SITE_NAME}`,
        description: cat.blurb,
        url,
        inLanguage: "en-US",
        isPartOf: { "@type": "WebSite", name: SITE_NAME, url: SITE_ORIGIN },
        hasPart: items.map((a) => ({
          "@type": "Article",
          headline: a.title,
          description: a.seoDek || a.dek,
          url: `${SITE_ORIGIN}/articles/${a.slug}`,
          datePublished: a.isoDate || a.date,
        })),
      },
      breadcrumb: breadcrumbLd([
        ["Home", `${SITE_ORIGIN}/`],
        [cat.label, null],
      ]),
      prose: hubProse(cat.label, `${cat.blurb} ${items.length} entries from The Talus Field's Yosemite field journal.`, articleLinkList(items)),
    };
  }

  const known = {
    "/": {
      title: HOME_TITLE,
      description: SITE_DEFAULT_DESC,
    },
    "/articles": {
      title: `Articles — ${SITE_NAME}`,
      description:
        "Every entry, in reverse chronological order. Yosemite trip planning, trails, wildlife, and seasonal guides.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Articles", null]],
      // CollectionPage whose mainEntity is the full catalog as an ItemList.
      // Mirrored client-side in app.jsx buildSeo so hydration replaces like
      // with like. Slim ListItems (url + name) avoid duplicating the Article
      // entities that live on the detail pages.
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        name: `Articles — ${SITE_NAME}`,
        url: `${SITE_ORIGIN}/articles`,
        description:
          "Every entry, in reverse chronological order. Yosemite trip planning, trails, wildlife, and seasonal guides.",
        inLanguage: "en-US",
        isPartOf: { "@type": "WebSite", name: SITE_NAME, url: SITE_ORIGIN },
        mainEntity: {
          "@type": "ItemList",
          numberOfItems: articles.length,
          itemListElement: articles.map((a, i) => ({
            "@type": "ListItem",
            position: i + 1,
            url: `${SITE_ORIGIN}/articles/${a.slug}`,
            name: a.title,
          })),
        },
      },
    },
    "/planning": {
      title: `The Yosemite Planning Guide — ${SITE_NAME}`,
      description:
        "Plan a Yosemite trip in 2026: entrances, gateway towns, permits, Half Dome, accessibility, smoke season, month by month. A curated hub through the planning archive.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Planning Guide", null]],
      faq: [
        { q: "Do I need a reservation to enter Yosemite in 2026?", a: "No. The day-use vehicle reservation system is not in effect in 2026. A standard Yosemite entrance pass ($35 per vehicle, valid 7 days) is required." },
        { q: "What is the best time of year to visit Yosemite?", a: "Late May through early June for peak waterfalls and moderate crowds. September and October for warm days, smaller crowds, and golden light. July and August are the most crowded months. April has spring waterfalls but Tioga Road and Glacier Point Road are usually still closed." },
        { q: "How much does it cost to enter Yosemite?", a: "$35 per vehicle (7-day pass), $20 per person entering on foot or bike. Since January 1, 2026, international visitors pay a $100 per-person surcharge (age 16 and older). The America the Beautiful annual pass ($80 for U.S. residents, $250 for nonresidents) covers entry to all national parks for one year." },
        { q: "How long should I spend at Yosemite?", a: "Minimum two full days: one for the Valley floor, one for a second area like Glacier Point, Mariposa Grove, or Tioga Road. Three to four days lets you cover all of these without rushing. A single-day trip is doable but you'll be moving the entire time." },
        { q: "Is Yosemite open year-round?", a: "Yosemite Valley is open year-round. Tioga Road (Highway 120 through the park) is typically closed November through May. Glacier Point Road closes in late November and reopens around Memorial Day. Mariposa Grove is open year-round but the tram is seasonal. Some campgrounds have seasonal closures." }
      ],
    },
    "/checklist": {
      title: `The Yosemite First-Week Checklist — ${SITE_NAME}`,
      description:
        "A printable single-page checklist for planning a Yosemite trip in 2026: when to come, what to book, what to pack, gateway choice, and the non-negotiables. Free.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Planning Checklist", null]],
    },
    "/about": {
      title: `About — ${SITE_NAME}`,
      description:
        "About The Talus Field, an independent field journal of Yosemite kept by Cory Goehring, a resident of the park.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["About", null]],
    },
    "/kit": {
      // Kept in sync with the client entry in app.jsx buildSeo (the kit
      // branch) and the page's own h1/dek in page-kit.jsx — this side went
      // stale once and served a title the page never showed.
      title: `Packing checklists for Yosemite — ${SITE_NAME}`,
      description:
        "Three Yosemite packing checklists to tick off as you plan: a day pack, what an overnight adds, and the full car load. The small, easily forgotten things included.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Kit", null]],
      // One ItemList per packing list. Matches the @graph app.jsx builds
      // client-side from window.KIT, so JS and non-JS crawlers see the same
      // entities. Sourced from the kit.json mirror.
      jsonLd: {
        "@context": "https://schema.org",
        "@graph": kit.lists.map((list) => ({
          "@type": "ItemList",
          name: list.title,
          description: list.summary,
          numberOfItems: list.items.length,
          itemListOrder: "https://schema.org/ItemListOrderAscending",
          url: `${SITE_ORIGIN}/kit#${list.slug}`,
          itemListElement: list.items.map((it, i) => ({
            "@type": "ListItem",
            position: i + 1,
            name: it.name,
            description: it.note,
          })),
        })),
      },
    },
    "/places": {
      title: `The Directory — Yosemite lodging and guides — ${SITE_NAME}`,
      description:
        "A small, curated directory of Yosemite-area lodging, outfitters, and guiding services, drawn from twenty seasons.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Directory", null]],
    },
    "/advertise": {
      title: `List your business — ${SITE_NAME}`,
      description:
        "How to list a Yosemite-area lodge, inn, guide service, or outfitter on The Talus Field directory.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["List your business", null]],
    },
    "/newsletter": {
      title: `Sunday Field Notes — ${SITE_NAME}`,
      description:
        "A short weekly note on Yosemite when there is something to say. Free.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Newsletter", null]],
    },
    "/contact": {
      title: `Contact — ${SITE_NAME}`,
      description:
        "Send a note to the editor. Trip questions, corrections, press, or anything else.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Contact", null]],
    },
    "/privacy": {
      title: `Privacy Policy — ${SITE_NAME}`,
      description:
        "What information The Talus Field collects, how it is used, and your rights under GDPR and CCPA.",
    },
    "/terms": {
      title: `Terms of Service — ${SITE_NAME}`,
      description:
        "Terms governing the use of The Talus Field, including content licensing and limitations of liability.",
    },
    "/affiliate": {
      title: `Affiliate Disclosure — ${SITE_NAME}`,
      description:
        "How affiliate links work on The Talus Field, and the editorial standards that don't change for paid placements.",
    },
    "/guide": {
      title: `The Field Guide — ${SITE_NAME}`,
      description:
        "The offline Yosemite guide: 81 entries with tappable GPS, time budgets, and crowd swaps, all 57 day hikes, a drive-order trip planner, and a topo map that works when service dies.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["The Field Guide", null]],
      // On sale since the July 2026 flip (GUIDE_ON_SALE in page-guide.jsx):
      // the page carries the live buy box.
      // FAQ pairs mirror GUIDE_FAQ in page-guide.jsx and the known.guide
      // entry in app.jsx's buildSeo. All three carry the same questions and
      // answers, kept in sync by hand (the /partners pattern): the published
      // page copy is the canonical text.
      faq: [
        {
          q: "Does it really work with no cell service?",
          a: "Yes. One tap downloads the whole guide, about 70 MB: every entry, the photos on file, all 57 hike tracks, and a topographic map of the park. A few entries still show a stand-in photo rather than the place itself. Only the live extras need signal: webcams, entrance waits, and fresh weather and program updates.",
        },
        {
          q: "Is it an App Store app?",
          a: "No. It is a web app you add to your home screen in one step, on iPhone or Android. No store account, no install wait, no version to manage. Once it is there it looks and behaves like a native app.",
        },
        {
          q: "What happens right after I pay?",
          a: "Stripe handles checkout. Within about a minute you get an email with a sign-in link and a 6-digit code. Both keep working for the full 18 months, so you can sign in on a new device whenever you like.",
        },
        {
          q: "How many devices can I use it on?",
          a: "Every device you personally own. Phone at the trailhead, tablet in the car, laptop the night before. The same code signs them all in.",
        },
        {
          q: "Is it a subscription?",
          a: "No. You pay $3.99 once and access runs 18 months. Nothing auto-renews. Near the end you are offered a discounted renewal, and if you do nothing, access simply ends.",
        },
        {
          q: "What if I lose the email or can't sign in?",
          a: "Email cory@thetalusfieldjournal.com and it gets sorted. The sign-in link and the code stay reusable for the whole 18 months, so finding the original email is usually the fix.",
        },
        {
          q: "What is the refund policy?",
          a: "If the guide does not work as described, email within 30 days of purchase and it is refunded in full. After a refund the access code is deactivated. The full policy is on the terms page.",
        },
        {
          q: "What do I get that the free site doesn't already give me?",
          a: "The complete library: 81 entries including the 37-entry Secret Guide, all 57 day hikes with GPS tracks and elevation profiles, the drag-and-drop trip builder, and the offline download. The free site keeps the articles, the trip map, the itineraries, and the conditions board.",
        },
        {
          q: "Does the guide change after I buy it?",
          a: "Yes. Updates, seasonal addenda, and Secret Guide additions push silently through your access window. Nothing to re-download, nothing extra to pay.",
        },
      ],
    },
    "/films": {
      title: `Moving Pictures — the Yosemite Nature Notes film archive — ${SITE_NAME}`,
      description:
        "The complete Yosemite Nature Notes film series from the National Park Service, grouped by subject. Public domain, free to watch, most under ten minutes.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Films", null]],
      // ItemList of VideoObject nodes, one per episode, built from the
      // videos.json mirror. Matches the shape app.jsx builds client-side from
      // videos-data.js so JS and non-JS crawlers see the same entity.
      //
      // uploadDate is emitted only for episodes that carry a sourced `uploaded`
      // date. Google requires the field, and its absence made all 40 items
      // invalid in Search Console, but a date is never derived from the bare
      // publication `year`: inventing a month and day to satisfy a validator
      // would publish a false fact. Fill the gaps with
      // scripts/fetch-video-dates.mjs, which reads each watch page.
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "ItemList",
        name: "Yosemite Nature Notes — the film archive",
        url: `${SITE_ORIGIN}/films`,
        numberOfItems: videos.length,
        // ListItem wrappers, not bare VideoObjects with a position property:
        // schema.org puts position on the ListItem, and validators reject the
        // flattened form for video rich results.
        itemListElement: videos.map((ep, i) => ({
          "@type": "ListItem",
          position: i + 1,
          item: {
            "@type": "VideoObject",
            name: ep.title,
            description: ep.dek,
            thumbnailUrl: `https://i.ytimg.com/vi/${ep.youtubeId}/hqdefault.jpg`,
            embedUrl: `https://www.youtube-nocookie.com/embed/${ep.youtubeId}`,
            ...(ep.uploaded ? { uploadDate: ep.uploaded } : {}),
            publisher: { "@type": "Organization", name: "National Park Service" },
            isAccessibleForFree: true,
          },
        })),
      },
    },
    "/search": {
      title: `Search — ${SITE_NAME}`,
      description:
        "Search every article, section, and page in The Talus Field: Yosemite planning notes, trail reports, wildlife and natural history, and seasonal guides.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Search", null]],
      // Search-results pages are thin and duplicative by nature, and every
      // ?q= is another near-identical URL. Kept out of the index, but crawled
      // for its links, which is why the HUB_PROSE entry is a contents list.
      robots: "noindex, follow",
    },
    "/explore": {
      title: `Site index — every page on the site — ${SITE_NAME}`,
      description:
        "Every page in The Talus Field, grouped and described: the sections, the Park Bulletin, the Nature Notes archive and films, the map, lodging, and the Field Guide app.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Site index", null]],
    },
    "/conditions": {
      title: `Yosemite Conditions — webcams, waits, and weather — ${SITE_NAME}`,
      description:
        "Live Yosemite webcams, entrance wait times, and elevation-aware weather forecasts on one page. Check it the morning you drive in.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Conditions", null]],
    },
    "/now": {
      title: `The Park Bulletin — what's happening in Yosemite right now — ${SITE_NAME}`,
      description:
        "Everything happening in Yosemite on one page: closures, roads, free ranger programs, dated events, trail status, hours, and phone numbers, updated each Guide edition.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["The Park Bulletin", null]],
    },
    "/widget": {
      title: `Yosemite Conditions Widget — free embed for area businesses — ${SITE_NAME}`,
      description:
        "A free embeddable box with live Yosemite entrance waits and the three-day Valley forecast, for gateway hotels, rental hosts, and tour operators. One script tag.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Widget", null]],
    },
    "/partners": {
      // B2B pitch page (MONETIZATION-IDEAS.md 2.4). FAQ answers mirror the
      // published copy in page-partners.jsx; keep the two in sync.
      title: `Group Codes — the Yosemite Field Guide for your guests — ${SITE_NAME}`,
      description:
        "Yosemite-area hotels, inns, rental hosts, and property managers: buy The Talus Field Guide in packs and give every guest a code. Offline app, 18 months of access, nothing to install on your side.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Group codes", null]],
      // Edge-only FAQ: the client entry in app.jsx carries none, so this
      // copy survives hydration on direct loads. A client-side faq added
      // later REPLACES it on first paint (the /planning drift) — change
      // both sides together or neither.
      faq: [
        {
          q: "What is a group code?",
          a: "One code is one guest's full access to The Talus Field Guide: the entire stop library across the Valley, Glacier Point and Mariposa Grove, Tuolumne, and Hetch Hetchy, the 37-entry Secret Guide, the trip planner with calendar export, park programs and weather on their dates, and the roughly 50 MB offline download. Access runs 18 months from the day the guest redeems, on every device they own.",
        },
        {
          q: "What do group codes cost?",
          a: "Partner pricing is quoted per property rather than published, because a single vacation rental and a management company covering every booking are not the same number. Write with the property, the town, and roughly how many bookings a year you would cover, and a quote comes back. The guide sells to the public at $3.99 a copy.",
        },
        {
          q: "Do guests need to install an app?",
          a: "No. The guide is a web app. It opens in the browser and can be added to a home screen in one step, which is what makes the offline download work. There is nothing for the property to install, host, or maintain.",
        },
        {
          q: "What happens to codes guests never redeem?",
          a: "Unredeemed codes stay yours. They do not expire on the shelf inside the season they were bought for, and a code that goes unused on one booking can go to the next guest instead.",
        },
      ],
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "Service",
        name: "Talus Field Guide group codes for lodging",
        description:
          "Bulk access codes to The Talus Field Guide, an offline Yosemite field guide app, for gateway hotels, inns, vacation rental hosts, and property managers to give to their guests.",
        provider: { "@id": AUTHOR_ID },
        areaServed: { "@type": "Place", name: "Yosemite National Park" },
        audience: { "@type": "BusinessAudience", name: "Lodging and hospitality operators" },
        url: `${SITE_ORIGIN}/partners`,
      },
    },
    "/consult": {
      title: `Field Consult — thirty minutes on your Yosemite plan — ${SITE_NAME}`,
      description:
        "A one-on-one planning consult with a Yosemite naturalist: your dates, group, and constraints, turned into a plan that fits the park. $95, thirty minutes, a few slots a month.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Field consult", null]],
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "Service",
        name: "Yosemite field consult",
        description:
          "A thirty-minute one-on-one Yosemite trip-planning consult with a resident naturalist, by call or as a written plan.",
        provider: { "@id": AUTHOR_ID },
        areaServed: { "@type": "Place", name: "Yosemite National Park" },
        url: `${SITE_ORIGIN}/consult`,
      },
    },
    "/stay": {
      // The standing lodging board. Evergreen by the same rule as the event
      // pages: no year and no rate anywhere in the copy, so the page does not
      // reset each season. FAQ answers come from the published bodies
      // (where-to-stay-in-yosemite, yosemite-gateway-towns-compared) per the
      // no-invented-facts rule.
      title: `Where to Stay in Yosemite — in-park lodging and gateway towns — ${SITE_NAME}`,
      description:
        "Every place to sleep in and around Yosemite, compared honestly: the six in-park lodges and camps, the five gateway towns with real drive times, and how the 366-day booking window actually works.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Where to stay", null]],
      // Edge-only FAQ: the client entry in app.jsx carries none, so this
      // copy survives hydration on direct loads. A client-side faq added
      // later REPLACES it on first paint (the /planning drift) — change
      // both sides together or neither.
      faq: [
        {
          q: "Where should you stay in Yosemite?",
          a: "Inside the park if you can get a bed, because the park is at its best in the first two hours and last two hours of the day, when day visitors are still on the road. Yosemite Valley Lodge is the correct answer for most first-time visitors with a hotel budget; Housekeeping Camp suits families who want to half-camp; Curry Village suits hikers on a budget; the Ahwahnee is for the occasion that justifies it.",
        },
        {
          q: "How do you book lodging inside Yosemite?",
          a: "Every hotel, lodge, and tent cabin inside the park is run by a single concessioner and books through travelyosemite.com. Reservations open 366 days in advance on a rolling basis, and for peak summer dates at the Valley properties, availability at the moment of release is measured in minutes.",
        },
        {
          q: "What do you do if Yosemite lodging is sold out?",
          a: "Rooms come back. Cancellation policies mean people drop reservations continuously, with a distinct wave in the final four to six weeks before any date, so checking the site daily at varied times genuinely works. Otherwise the gateway towns are the real alternative, and winter is dramatically easier and cheaper than summer.",
        },
        {
          q: "Which gateway town is best for Yosemite?",
          a: "El Portal is 25 to 35 minutes from Yosemite Valley and the strongest choice if you can get a room. Mariposa, 45 minutes to an hour out on Highway 140, is the safest first-timer's pick and the most full-service. Groveland is the character pick on Highway 120, Oakhurst suits trips centered on Wawona and the Mariposa Grove, and Lee Vining is the east-side base while Tioga Pass is open.",
        },
      ],
    },
    "/firefall": {
      // Evergreen event page: no year in the URL or copy, so the same page
      // accrues rank every February instead of resetting on a dated slug.
      // FAQ answers come from the published article body
      // (bodies/horsetail-fall-firefall.jsx) per the no-invented-facts rule.
      title: `The Yosemite Firefall — dates, conditions, and how to plan — ${SITE_NAME}`,
      description:
        "When the Horsetail Fall firefall happens, the three conditions that must line up, and how to plan a February evening around uncertain odds. By a park resident.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Firefall", null]],
      // Edge-only FAQ: the client entry in app.jsx carries none, so this
      // copy survives hydration on direct loads. A client-side faq added
      // later REPLACES it on first paint (the /planning drift) — change
      // both sides together or neither.
      faq: [
        {
          q: "When is the Yosemite firefall?",
          a: "The sun angle that lights Horsetail Fall runs roughly the second week of February through the last week, with the strongest color usually in the middle of that span. The glow builds for a few minutes, peaks near sunset, and is finished about ten minutes later.",
        },
        {
          q: "What has to happen for the firefall to appear?",
          a: "Three independent conditions must hold at once: water in Horsetail Fall from recent rain or snowmelt, a clear western horizon at sunset, and the mid-to-late-February sun angle. Any one failing cancels the show entirely.",
        },
        {
          q: "Where do you watch the firefall from?",
          a: "The classic viewing zone is Northside Drive near the El Capitan Picnic Area. Expect to park at a designated area, often Yosemite Falls parking, walk a mile or more each way, and be in place at least an hour before sunset.",
        },
        {
          q: "Do you need a reservation to see the firefall?",
          a: "In some years the park has required reservations for February weekends, along with parking restrictions and road closures. The rules change year to year; check the NPS Horsetail Fall page and current conditions in the week before your trip.",
        },
      ],
    },
    "/tioga-opening": {
      // Evergreen event page: no year in the URL or copy. FAQ answers come
      // from the published article body
      // (bodies/tioga-road-opening-weekend-2026.jsx) per the
      // no-invented-facts rule; anything annual points at NPS.
      title: `The Tioga Road Opening — when it opens and how to plan — ${SITE_NAME}`,
      description:
        "How the Tioga Road opening actually works: why the date is announced only days ahead, what is really open in week one, and how to drive the early season well. By a park resident.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Tioga opening", null]],
      // Edge-only FAQ: the client entry in app.jsx carries none, so this
      // copy survives hydration on direct loads. A client-side faq added
      // later REPLACES it on first paint (the /planning drift) — change
      // both sides together or neither.
      faq: [
        {
          q: "When does Tioga Road open?",
          a: "There is no fixed date: the road opens when plow crews finish, and the park announces it only days ahead. The long-term average opening is the end of May; light snow years have opened in mid-May, and heavy years push the opening into June or later. It closes with the first lasting snow, typically in November.",
        },
        {
          q: "Is there gas, food, or water on Tioga Road?",
          a: "Crane Flat, at the road's west end, has pay-at-pump gas; the next fuel is Lee Vining on the east side of the pass. In the early season there is no potable water and nothing to buy along the road, and services at Tuolumne Meadows come online weeks after the road opens. Bring everything.",
        },
        {
          q: "How long does it take to drive Tioga Road?",
          a: "About 39 miles from Crane Flat to the Tioga Pass entrance station, roughly 90 minutes one way without stops. With Olmsted Point, Tenaya Lake, and Tuolumne Meadows it is a full day, and adding Lee Vining and Mono Lake makes it a long one.",
        },
        {
          q: "Do I need a reservation to drive Tioga Road?",
          a: "A standard park entrance pass is required. Whether a day-use reservation system also applies changes year to year; check the NPS Yosemite site for the current season's rules before you commit.",
        },
      ],
    },
    "/webcams": {
      title: `Yosemite Webcams — the live views worth checking — ${SITE_NAME}`,
      description:
        "Live Yosemite webcams: Half Dome, Yosemite Falls, El Capitan and Wawona, what each camera shows, how often it refreshes, and how to read them before you drive in.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Webcams", null]],
      faq: [
        {
          q: "Are there live webcams in Yosemite?",
          a: "Yes. The Yosemite Conservancy runs the public cameras, four of which are embedded here: Half Dome from Ahwahnee Meadow, Upper Yosemite Fall, El Capitan from Turtleback Dome, and Wawona. They are still-image cameras that refresh on the order of minutes rather than video streams, so a reload will not always change the picture.",
        },
        {
          q: "Is there a webcam at Tuolumne Meadows or Tioga Pass?",
          a: "Not among the public Yosemite Conservancy cameras, and it is the most requested view the park does not have. For the high country the substitutes are the NPS Tioga Road page for plowing and opening status in spring, and the park's current conditions page once the road is open.",
        },
        {
          q: "Why does the Yosemite Falls webcam show no waterfall?",
          a: "Because there is no waterfall. Yosemite Falls is fed by snowmelt from a shallow basin above the rim and is usually dry by late August, staying dry until the first storms of November. The camera is working; the fall is seasonal.",
        },
      ],
    },
    "/distances": {
      title: `Yosemite Drive Times — every gateway town, in one table — ${SITE_NAME}`,
      description:
        "How far Yosemite Valley is from El Portal, Mariposa, Groveland, Oakhurst and Lee Vining: miles, drive times, entrances, elevations and what the season does to each route.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Distances", null]],
      // Edge-only FAQ, answering the distance queries the gateway article ranks
      // top-three for and earns no clicks on. Every figure is quoted from that
      // article's published body, which is the canonical source for drive times.
      faq: [
        {
          q: "How far is Groveland from Yosemite Valley?",
          a: "About 41 miles and 65 to 80 minutes on Highway 120, entering the park at the Big Oak Flat Entrance, which is about 24 miles and 30 to 40 minutes from town on a winding road. Groveland sits at about 3,100 feet, the highest of the western gateways, and gets chain controls in winter that the Highway 140 towns do not.",
        },
        {
          q: "How far is Oakhurst from Yosemite Valley?",
          a: "About 50 miles and 75 to 90 minutes on Highway 41, which is the longest drive to the Valley of the four year-round gateway towns. Oakhurst is much closer to the park's south end: about 14 miles and 20 to 25 minutes to the South Entrance, with the Mariposa Grove welcome plaza immediately inside the gate.",
        },
        {
          q: "What is the closest town to Yosemite Valley?",
          a: "El Portal, at about 14 miles and 25 to 35 minutes on Highway 140. It sits at about 1,900 feet, the lowest of the gateway towns, on the most reliable year-round route into the park.",
        },
        {
          q: "How long does it take to drive across Yosemite?",
          a: "Longer than the map suggests. Yosemite Valley to Glacier Point is roughly an hour when that road is open, the Valley to Tuolumne Meadows is about an hour and a half, and Hetch Hetchy is a dead end serving no through route. A day that crosses the park is a driving day.",
        },
      ],
    },
    "/half-dome-lottery": {
      // Evergreen event page: no current year in the URL or copy, and no
      // promise about a season that has not happened. Published statistics for
      // seasons already past are the deliberate exception, labeled by season.
      // FAQ answers come from the page's own published body
      // (page-half-dome-lottery.jsx), which absorbed the retired article
      // /articles/half-dome-permit-lottery-2026 in August 2026.
      title: `The Half Dome Lottery — calendar, odds, and strategy — ${SITE_NAME}`,
      description:
        "Both Half Dome permit lotteries explained: the March preseason draw, the daily lottery almost nobody uses, the published NPS odds, and the strategy that actually works. By a park resident.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Half Dome lottery", null]],
      // Edge-only FAQ: the client entry in app.jsx carries none, so this
      // copy survives hydration on direct loads. A client-side faq added
      // later REPLACES it on first paint (the /planning drift) — change
      // both sides together or neither.
      faq: [
        {
          q: "When is the Half Dome permit lottery?",
          a: "There are two. The preseason lottery accepts applications on Recreation.gov for the month of March, with results emailed in mid-April. The daily lottery runs every day the cables are up: apply two days before your hike date, between midnight and 4 p.m. Pacific, with results late that evening.",
        },
        {
          q: "How hard is it to win a Half Dome permit?",
          a: "In the 2024 season the National Park Service recorded 35,289 preseason applications with a 22% success rate, and 35,561 daily-lottery applications with a 19% success rate. Weekdays draw meaningfully better odds than weekends in the daily lottery, 22% against 14%, and late-season weekdays, late August through the October cable takedown, are the best draw of the year.",
        },
        {
          q: "What are the odds of winning the Half Dome daily lottery?",
          a: "About 19% of daily-lottery applications succeeded in the 2024 season, split 22% on weekdays and 14% on weekends. Because each day's draw is independent, applying on five eligible weekday mornings works out to roughly a two in three chance of winning at least once, which is why the hike is best planned for the middle of a trip rather than its first day.",
        },
        {
          q: "How much does a Half Dome permit cost?",
          a: "There is a non-refundable application fee charged per application rather than per person, plus a per-person recreation fee if you win. Both were $10 in the 2024 season, so a group of four that applied once and won paid $50 in total. The recreation fee is refundable if you cancel by 11:59 p.m. Pacific the day before your hike date, or if the cables are not up on your date. Check the NPS permit page for the current season's amounts.",
        },
        {
          q: "How many people can be on one Half Dome permit application?",
          a: "Up to six, in both lotteries, and the group hikes together. Larger parties split across two applications under two different permit holders, which are entered independently. Each person may appear as permit holder or alternate on only one preseason application; appearing on two cancels all of them without a refund.",
        },
        {
          q: "Can you hike Half Dome without a permit?",
          a: "No. While the cables are up, rangers check permits and photo ID at the base of the subdome, and hiking past the checkpoint without one is a federal violation with fines running to thousands of dollars. The legal alternative is a wilderness permit with a Half Dome add-on, drawn from a separate backpacker allocation.",
        },
        {
          q: "When are the Half Dome cables up?",
          a: "Typically from the Friday before Memorial Day until the day after the second Monday in October, shifting with snow and weather. Outside that window the cables are down and the summit route is not maintained.",
        },
      ],
    },
    "/itineraries": {
      title: `Yosemite Itineraries — day plans on the map — ${SITE_NAME}`,
      description:
        "Curated Yosemite itineraries for one, two, or three days, plus a half-day plan for late arrivals. Each opens as a ready-made trip on the interactive map.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Itineraries", null]],
      // Built from ITINERARY_TRIPS below (hand-maintained mirror of
      // itineraries-data.js — this Worker imports JSON mirrors only). Matches
      // the ItemList app.jsx builds client-side; update ITINERARY_TRIPS when a
      // plan's title or dek changes there.
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "ItemList",
        name: "Yosemite itineraries",
        url: `${SITE_ORIGIN}/itineraries`,
        numberOfItems: ITINERARY_TRIPS.length,
        itemListElement: ITINERARY_TRIPS.map((t, i) => ({
          "@type": "ListItem",
          position: i + 1,
          item: {
            "@type": "TouristTrip",
            name: t.name,
            description: t.description,
            url: `${SITE_ORIGIN}/itineraries#${t.id}`,
            touristType: "National park visitors",
          },
        })),
      },
    },
    "/map": {
      title: `Yosemite Trip Planner Map — ${SITE_NAME}`,
      description:
        "An interactive Yosemite map of vistas, trailheads, parking turnouts, picnic spots, and places to eat, with a trip builder. Curated by a resident of the park. Free with an email signup.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Map", null]],
      // Honest, static WebPage node. The pin list itself stays out of the
      // structured data until the new points pass a ground-truth check.
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "WebPage",
        name: `Yosemite Trip Planner Map — ${SITE_NAME}`,
        url: `${SITE_ORIGIN}/map`,
        description:
          "An interactive Yosemite map of vistas, trailheads, parking turnouts, picnic spots, and places to eat, with a trip builder. Curated by a resident of the park. Free with an email signup.",
        isAccessibleForFree: true,
        inLanguage: "en-US",
        about: {
          "@type": "Place",
          name: "Yosemite National Park",
          geo: { "@type": "GeoCoordinates", latitude: 37.8651, longitude: -119.5383 },
        },
      },
    },
  };

  const meta = known[path];
  if (!meta) return null;
  const seo = {
    title: meta.title,
    description: meta.description,
    canonical: `${SITE_ORIGIN}${path === "/" ? "/" : path}`,
    ogType: "website",
    image: SITE_DEFAULT_IMAGE,
    jsonLd: meta.jsonLd || null,
    breadcrumb: meta.breadcrumb ? breadcrumbLd(meta.breadcrumb) : null,
    faq: meta.faq ? faqLd(meta.faq) : null,
    robots: meta.robots || null,
    prose: HUB_PROSE[path] ? HUB_PROSE[path]() : null,
  };
  if (path === "/map") applyTripSeo(seo, searchParams);
  return seo;
}

// Unmatched SPA routes (typos, dead slugs, removed pages) used to fall through
// to the 200 SPA fallback and index as thin homepage duplicates. Serve them as
// real 404s with noindex instead; app.jsx renders the matching not-found view.
function notFoundSeo(pathname) {
  return {
    title: `Page not found — ${SITE_NAME}`,
    description:
      "That page does not exist on The Talus Field. The articles index, planning guide, and trip planner map are good places to reorient.",
    canonical: `${SITE_ORIGIN}${pathname}`,
    ogType: "website",
    image: SITE_DEFAULT_IMAGE,
    jsonLd: null,
    breadcrumb: null,
    faq: null,
    robots: "noindex, follow",
    status: 404,
    prose:
      `<h1>Page not found</h1><p>There is nothing at this address. The link may be old, or the page may have moved.</p>` +
      `<p>Good places to reorient: <a href="/articles">the articles index</a>, <a href="/planning">the planning guide</a>, or <a href="/map">the trip planner map</a>.</p>`,
  };
}

// Mirror of slugifyImage in components.jsx / the gen scripts: derive the
// responsive variant basename from an image path.
function slugifyImagePath(image) {
  const base = String(image).split("/").pop() || "";
  return base.toLowerCase().replace(/\.[^.]+$/, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

// Per-route hero LCP preload (C12), mirroring index.html's home-hero preload:
// a responsive AVIF imagesrcset so the browser fetches the LCP image during HTML
// parse, ahead of React. Null for external/missing images.
function heroPreloadTag(imagePath) {
  if (!imagePath || /^https?:/i.test(imagePath)) return null;
  const cleaned = imagePath.replace(/^\/+/, "");
  const slash = cleaned.lastIndexOf("/");
  const dir = slash >= 0 ? cleaned.slice(0, slash) : "";
  const base = `/${dir ? dir + "/" : ""}responsive/${slugifyImagePath(cleaned)}`;
  const srcset = [400, 800, 1200, 1600].map((w) => `${base}-${w}.avif ${w}w`).join(", ");
  return `<link rel="preload" as="image" type="image/avif" imagesrcset="${srcset}" imagesizes="(max-width: 700px) 100vw, 700px" fetchpriority="high" />`;
}

function escapeHtmlText(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export default {
  fetch(request, env) {
    // The asset layer answers requests that match real files before the
    // Worker runs, so `next()` here is always the SPA-fallback index.html
    // (or a 404-shaped asset response) — the same thing Pages' context.next()
    // returned. Keeping the old handler shape makes the port a two-line diff.
    return handleRequest({ request, env, next: () => env.ASSETS.fetch(request) });
  },
};

// Named exports for offline checks (scripts/, plain node): let a test call the
// route metadata logic and the crawler-visible related block without workerd's
// HTMLRewriter runtime.
export { seoForPath, relatedBlock };

// Permanent redirects, checked before any SEO work. The site had no redirect
// capability before the evergreen event pages landed (it is a Worker, not
// Pages, so there is no _redirects file); this table is the mechanism. Add an
// entry when a URL is retired or consolidated — e.g. if a year-stamped article
// slug ever folds into its evergreen event page — and crawlers get a real 301
// instead of a 404 or a duplicate.
const REDIRECTS = {
  // Retired August 2026. The dated article and the evergreen hub targeted the
  // identical intent and split it: 1,925 impressions and 9 clicks between them
  // over 90 days, both parked just below the fold with Google confidently
  // ranking neither. The article's content moved into the hub, which is the
  // URL that does not need re-slugging every March.
  "/articles/half-dome-permit-lottery-2026": "/half-dome-lottery",
};

// The apex is the canonical host, and www is bound as a second custom domain
// in wrangler.jsonc, so both served 200s for months: Search Console's Pages
// report carried separate rows for http://www, https://www and the apex of the
// same article, splitting signals across three URLs and producing duplicate
// rows in every report.
//
// Match the www host EXACTLY rather than testing "hostname !== apex". A
// not-equal guard would also fire on localhost under `wrangler dev` and on
// *.workers.dev preview deploys, redirecting every local request to production.
//
// This is the backstop, not the fix. Routing here is asset-first, so `/`, every
// real file and both sitemaps are served off the asset layer on www without the
// Worker ever running; only SPA routes reach this code. The zone-level Redirect
// Rule documented in DEPLOY.md is what covers the whole host.
const WWW_HOST = "www.thetalusfieldjournal.com";

async function handleRequest({ request, next, env }) {
  const url = new URL(request.url);
  if (url.hostname === WWW_HOST) {
    return Response.redirect(`${SITE_ORIGIN}${url.pathname}${url.search}`, 301);
  }
  const redirectTarget = REDIRECTS[url.pathname.replace(/\/+$/, "") || "/"];
  if (redirectTarget) {
    // Carry the query string across: a retired slug arriving as
    // ?utm_source=newsletter must keep its attribution on the other side.
    return Response.redirect(`${SITE_ORIGIN}${redirectTarget}${url.search}`, 301);
  }
  // Unknown SPA routes get a real 404 (with noindex + not-found prose) instead
  // of a 200 homepage clone. Real files never reach the Worker (asset-first
  // routing), so anything unmatched here is genuinely not a page.
  const seo = seoForPath(url.pathname, url.searchParams) || notFoundSeo(url.pathname);

  const response = await next();
  const ct = response.headers.get("content-type") || "";
  if (!ct.toLowerCase().includes("text/html")) return response;

  // Crawler-visible body text. Article routes fetch the committed prerendered
  // prose fragment (prefixed with the article <h1>); hub/section/not-found
  // routes carry their own fragment in seo.prose, <h1> included. Fails open:
  // any miss just leaves the SPA-only #root.
  let proseHtml = null;
  if (seo.prerenderSlug && env && env.ASSETS) {
    try {
      const pr = await env.ASSETS.fetch(new URL(`/prerender/${seo.prerenderSlug}.html`, url.origin));
      if (pr.ok) {
        proseHtml =
          `<h1>${escapeHtmlText(seo.articleTitle || "")}</h1>` +
          (await pr.text()) +
          relatedBlock(seo.prerenderSlug);
      }
    } catch (_e) { /* fail open: no injected prose */ }
  } else if (seo.prose) {
    proseHtml = seo.prose;
  }
  const heroPreload = seo.prerenderSlug ? heroPreloadTag(seo.heroImagePath) : null;
  // Route-aware static H1: the sr-only #seo-static-h1 in index.html carries the
  // homepage title for markup-only parsers. When a prose fragment is injected
  // it brings its own on-topic <h1>, so the static one is removed to avoid a
  // duplicate; otherwise it is rewritten to the route's title (site name
  // suffix stripped) so no route ships a topic-mismatched heading.
  const staticH1Text = proseHtml ? null : seo.title.replace(/\s+—\s+The Talus Field$/, "");

  const rewritten = new HTMLRewriter()
    .on("title", {
      element(el) {
        el.setInnerContent(seo.title);
      },
    })
    .on('meta[name="description"]', {
      element(el) {
        el.setAttribute("content", seo.description);
      },
    })
    .on('meta[name="twitter:title"]', {
      element(el) {
        el.setAttribute("content", seo.title);
      },
    })
    .on('meta[name="twitter:description"]', {
      element(el) {
        el.setAttribute("content", seo.description);
      },
    })
    .on('meta[name="twitter:image"]', {
      element(el) {
        el.setAttribute("content", seo.image);
      },
    })
    .on('meta[property="og:title"]', {
      element(el) {
        el.setAttribute("content", seo.title);
      },
    })
    .on('meta[property="og:description"]', {
      element(el) {
        el.setAttribute("content", seo.description);
      },
    })
    .on('meta[property="og:url"]', {
      element(el) {
        // Trip-share overrides set ogUrl to the full shared URL so scrapers
        // unfurl the specific trip; canonical stays the clean route.
        el.setAttribute("content", seo.ogUrl || seo.canonical);
      },
    })
    .on('meta[property="og:type"]', {
      element(el) {
        el.setAttribute("content", seo.ogType);
      },
    })
    .on('meta[property="og:image"]', {
      element(el) {
        el.setAttribute("content", seo.image);
      },
    })
    .on('meta[property="og:image:width"]', {
      element(el) {
        if (seo.imageWidth) el.setAttribute("content", String(seo.imageWidth));
      },
    })
    .on('meta[property="og:image:height"]', {
      element(el) {
        if (seo.imageHeight) el.setAttribute("content", String(seo.imageHeight));
      },
    })
    .on('link[rel="canonical"]', {
      element(el) {
        el.setAttribute("href", seo.canonical);
      },
    })
    .on('meta[name="robots"]', {
      element(el) {
        if (seo.robots) el.setAttribute("content", seo.robots);
      },
    })
    .on('meta[property="og:image:alt"]', {
      element(el) {
        if (seo.imageAlt) el.setAttribute("content", seo.imageAlt);
      },
    })
    .on("head", {
      element(el) {
        if (seo.articleOg) {
          const og = seo.articleOg;
          if (og.publishedTime) {
            el.append(
              `<meta property="article:published_time" content="${og.publishedTime}" />`,
              { html: true }
            );
          }
          if (og.modifiedTime) {
            el.append(
              `<meta property="article:modified_time" content="${og.modifiedTime}" />`,
              { html: true }
            );
          }
          if (og.author) {
            el.append(
              `<meta property="article:author" content="${og.author}" />`,
              { html: true }
            );
          }
          if (og.section) {
            el.append(
              `<meta property="article:section" content="${og.section}" />`,
              { html: true }
            );
          }
        }
        if (seo.jsonLd) {
          el.append(
            `<script type="application/ld+json" id="ld-page">${safeJsonForScript(seo.jsonLd)}</script>`,
            { html: true }
          );
        }
        if (seo.breadcrumb) {
          el.append(
            `<script type="application/ld+json" id="ld-breadcrumb">${safeJsonForScript(seo.breadcrumb)}</script>`,
            { html: true }
          );
        }
        if (seo.faq) {
          el.append(
            `<script type="application/ld+json" id="ld-faq">${safeJsonForScript(seo.faq)}</script>`,
            { html: true }
          );
        }
        if (seo.trail) {
          el.append(
            `<script type="application/ld+json" id="ld-trail">${safeJsonForScript(seo.trail)}</script>`,
            { html: true }
          );
        }
        if (heroPreload) {
          el.append(heroPreload, { html: true });
        }
      },
    })
    .on("#home-shell", {
      element(el) {
        // index.html ships the homepage's above-the-fold markup statically so
        // "/" paints on the first byte (see the comment there and
        // scripts/gen-home-shell.mjs). "/" is served straight off the asset
        // layer and never reaches this Worker, so every request that DOES
        // reach here is another route: drop the block before the browser can
        // paint a hero that belongs to a different page.
        el.remove();
      },
    })
    .on("#root", {
      element(el) {
        // Inject the prose fragment (article body or hub summary, <h1>
        // included) as the first child of #root so non-JS crawlers see
        // route-specific text. The client boots with createRoot().render()
        // which replaces #root's children, and app.jsx also removes
        // #prerender-prose on boot, so JS users only ever see React's copy.
        if (proseHtml) {
          el.prepend(`<div id="prerender-prose">${proseHtml}</div>`, { html: true });
        } else if (staticH1Text) {
          // Routes with no prose fragment still need one heading for parsers
          // that read the markup without running JavaScript (Bing's auditor is
          // the notable one). This used to be a permanent sr-only element in
          // index.html; it moved here when the homepage gained a real static
          // <h1> in its shell, which would otherwise have made "/" ship two.
          // app.jsx removes it on boot, so JS clients see exactly one <h1>.
          el.prepend(
            `<h1 id="seo-static-h1" style="position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap;border:0;">${escapeHtmlText(staticH1Text)}</h1>`,
            { html: true }
          );
        }
      },
    })
    .transform(response);

  // Not-found routes ship the SPA shell (so the client can render its own
  // not-found view) but with a real 404 status for crawlers and link checkers.
  if (seo.status === 404) {
    return new Response(rewritten.body, {
      status: 404,
      statusText: "Not Found",
      headers: rewritten.headers,
    });
  }
  return rewritten;
}
