// Edge SEO Worker for the editorial site (the `main` entry in wrangler.jsonc,
// serving alongside the static assets). Rewrites the static index.html on the
// edge so each route ships its own <title>, meta description, canonical,
// Open Graph, Twitter, and JSON-LD structured data — without a build step.
//
// Why this exists: the editorial site is a client-rendered SPA. Without this
// rewrite, every URL serves the homepage's <head>, so non-JS crawlers (most
// AI bots, social card scrapers, Bingbot under load) see the same metadata
// for every article. The browser-side code in app.jsx still updates these
// tags after hydration; this just makes the static HTML correct from the
// first byte.
//
// History: this began life as the Cloudflare Pages Function
// functions/_middleware.js. When the site moved from Pages to a Worker with
// static assets, Pages Functions stopped executing, so the same logic now
// runs as the Worker's fetch handler. Requests that match a real file
// (/dist/*, /styles.css, /img/*, /prerender/*, …) are served by the asset
// layer and never reach this code; only SPA routes (no matching file) run it,
// which reproduces the old context.next() flow via env.ASSETS.fetch.

import articles from "../articles.json" with { type: "json" };
import categories from "../categories.json" with { type: "json" };
import videos from "../videos.json" with { type: "json" };
import kit from "../kit.json" with { type: "json" };
import bulletin from "../bulletin.json" with { type: "json" };
import tripPoints from "../trip-points.json" with { type: "json" };

const SITE_ORIGIN = "https://thetalusfieldjournal.com";
const SITE_NAME = "The Talus Field";
const SITE_TAGLINE = "Yosemite, written from inside it";
// 1200x630 landscape card generated by scripts/gen-responsive-images.mjs —
// matches the og:image:width/height declared in index.html.
const SITE_DEFAULT_IMAGE = `${SITE_ORIGIN}/img/og-default.jpg`;
const SITE_DEFAULT_DESC =
  "A field journal of Yosemite National Park, kept by a resident. Trails, planning notes, wildlife, and essays on the park's seasons and life.";
const AUTHOR_NAME = "Cory Goehring";
// Single author node lives in index.html (<script id="ld-person">). Article
// schema references it by @id so there is one Person entity for the whole site.
const AUTHOR_ID = `${SITE_ORIGIN}/#person-cory-goehring`;
const PUBLISHER_LOGO = `${SITE_ORIGIN}/img/talus-field-mark-square.png`;

function absoluteImage(url) {
  if (!url) return SITE_DEFAULT_IMAGE;
  if (/^https?:/i.test(url)) return url;
  return `${SITE_ORIGIN}/${url.replace(/^\//, "")}`;
}

function safeJsonForScript(obj) {
  // Defend against premature </script> termination if any string contains it.
  return JSON.stringify(obj).replace(/<\/(script)/gi, "<\\/$1");
}

// Build a BreadcrumbList from an array of [name, url] (last item omits url).
function breadcrumbLd(crumbs) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: crumbs.map(([name, url], i) => {
      const item = { "@type": "ListItem", position: i + 1, name };
      if (url) item.item = url;
      return item;
    }),
  };
}

// Build a FAQPage from an array of {q, a} pairs.
function faqLd(pairs) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: pairs.map(({ q, a }) => ({
      "@type": "Question",
      name: q,
      acceptedAnswer: { "@type": "Answer", text: a },
    })),
  };
}

// Build a TouristAttraction for a trail guide from the article's `trail` facts
// (seo-data.json). HikingTrail is not a type Google parses for rich results, so
// the hike stats ride along as additionalProperty PropertyValues. Numbers come
// from the article body; geo is emitted only when a trailhead coord is verified.
function trailLd(a, url) {
  const t = a.trail;
  const props = [];
  if (t.distance) props.push({ "@type": "PropertyValue", name: "Distance", value: t.distance });
  if (t.elevationGain) props.push({ "@type": "PropertyValue", name: "Elevation gain", value: t.elevationGain });
  if (t.difficulty) props.push({ "@type": "PropertyValue", name: "Difficulty", value: t.difficulty });
  const ld = {
    "@context": "https://schema.org",
    "@type": "TouristAttraction",
    name: t.name || a.title,
    description: a.seoDek || a.dek,
    url,
    touristType: "Hikers",
    isAccessibleForFree: true,
    containedInPlace: { "@type": "Place", name: "Yosemite National Park" },
  };
  if (props.length) ld.additionalProperty = props;
  if (t.geo && typeof t.geo.lat === "number" && typeof t.geo.lng === "number") {
    ld.geo = { "@type": "GeoCoordinates", latitude: t.geo.lat, longitude: t.geo.lng };
  }
  return ld;
}

// ---------------------------------------------------------------------------
// Crawler-visible prose for non-article routes. Articles get their committed
// /prerender/<slug>.html fragment; hub/section pages get these fragments,
// built from the same JSON mirrors this Worker already imports (so the lists
// stay fresh with the catalog) plus short hand-written intros. Injected into
// #root exactly like article prose so non-JS crawlers (Bing, AI answer
// engines, social scrapers) see route-specific headings and body text instead
// of the homepage-generic <noscript>. Each fragment carries its own <h1>; the
// static #seo-static-h1 is removed whenever a fragment is injected and
// rewritten to the route title otherwise.
// ---------------------------------------------------------------------------
function articleLinkList(list) {
  return `<ul>${list
    .map((a) => `<li><a href="/articles/${a.slug}">${escapeHtmlText(a.title)}</a>: ${escapeHtmlText(a.seoDek || a.dek)}</li>`)
    .join("")}</ul>`;
}

function hubProse(h1, intro, extraHtml) {
  return `<h1>${escapeHtmlText(h1)}</h1><p>${escapeHtmlText(intro)}</p>${extraHtml || ""}`;
}

// Hand-maintained mirror of itineraries-data.js: drives both the TouristTrip
// ItemList and the /itineraries crawler prose. Update alongside that file.
const ITINERARY_TRIPS = [
  {
    id: "1day",
    name: "One day in the Valley",
    description:
      "The Valley floor, west to east, morning to dinner. Arrive early, park once if you can, and let the day move at walking pace between the famous walls.",
  },
  {
    id: "2day",
    name: "The Valley, then the rim",
    description:
      "Day one on the Valley floor. Day two up Glacier Point Road, stopping in trailhead order, for the views that look back down on everything you walked the day before.",
  },
  {
    id: "3day",
    name: "Valley, rim, and high country",
    description:
      "The two-day plan, then a third day on Tioga Road, west to east toward the pass. The high country is a different park: granite domes, subalpine lakes, and half the crowd.",
  },
  {
    id: "halfday",
    name: "Arriving at two",
    description:
      "The honest plan for a late arrival: skip the trailheads, take the meadows and the river, and end at the pizza deck while the light is still on the walls.",
  },
];

// Crawler prose for the static hub routes, keyed by path. Values are thunks so
// only the matched route's fragment is built per request. Short hand-written
// intros in the house voice; lists are generated from the imported JSON
// mirrors so they never go stale against the catalog.
const HUB_PROSE = {
  "/articles": () =>
    hubProse(
      "Articles",
      "Every entry in the journal, newest first: Yosemite trip planning, trails and hikes, wildlife and nature, and seasonal guides, written from inside the park.",
      articleLinkList(articles)
    ),
  "/planning": () =>
    hubProse(
      "The Yosemite Planning Guide",
      "Planning advice from inside the park, checked on foot: entrances and getting here, gateway towns, permits, Half Dome, accessibility, smoke season, and the seasonal calendar. The planning archive, curated:",
      articleLinkList(articles.filter((a) => a.cat === "planning"))
    ),
  "/checklist": () =>
    hubProse(
      "The Yosemite First-Week Checklist",
      "A printable single-page checklist for the first week of planning a Yosemite trip: when to come, what to book and in what order, what to pack, which gateway to base in, and the non-negotiables. Free, no signup required."
    ) +
    `<p>The reasoning behind each line item lives in <a href="/planning">the Planning Guide</a>; the packing details live in <a href="/kit">the kit lists</a>.</p>`,
  "/kit": () =>
    hubProse(
      "Kit: what I carry in Yosemite",
      "Three packing lists with the reasoning behind every item: a day pack, what an overnight adds, and the full car load."
    ) +
    kit.lists
      .map(
        (list) =>
          `<h2>${escapeHtmlText(list.title)}</h2><p>${escapeHtmlText(list.summary)}</p><ul>${list.items
            .map((it) => `<li>${escapeHtmlText(it.name)}${it.note ? `: ${escapeHtmlText(it.note)}` : ""}</li>`)
            .join("")}</ul>`
      )
      .join(""),
  "/films": () =>
    hubProse(
      "Moving Pictures: the Yosemite Nature Notes film archive",
      "The complete Yosemite Nature Notes series from the National Park Service, grouped by subject. Public domain, free to watch, most under ten minutes."
    ) +
    `<ul>${videos.map((ep) => `<li>${escapeHtmlText(ep.title)}: ${escapeHtmlText(ep.dek)}</li>`).join("")}</ul>`,
  "/itineraries": () =>
    hubProse(
      "Yosemite itineraries: day plans on the map",
      "Curated Yosemite itineraries for one, two, or three days, plus a half-day plan for late arrivals. Each opens as a ready-made trip on the interactive trip planner map."
    ) +
    ITINERARY_TRIPS.map((t) => `<h2>${escapeHtmlText(t.name)}</h2><p>${escapeHtmlText(t.description)}</p>`).join("") +
    `<p>Open any plan on <a href="/map">the trip planner map</a>, or check <a href="/conditions">current conditions</a> before you drive in.</p>`,
  "/map": () =>
    hubProse(
      "The Yosemite trip planner map",
      "An interactive map of Yosemite National Park: vistas, trailheads, parking turnouts, picnic spots, and places to eat, each pin curated and written by a resident of the park. Filter pins by category, search by name, and assemble stops into a trip you can share by link, email to yourself, or open in Google Maps for driving directions. The full map opens with a free newsletter signup."
    ) +
    `<p>Prefer a ready-made plan? Start from <a href="/itineraries">the curated itineraries</a>. Planning the drive in? Check <a href="/conditions">webcams, entrance waits, and weather</a>.</p>`,
  "/conditions": () =>
    hubProse(
      "Yosemite conditions: webcams, waits, and weather",
      "The morning-of page: live Yosemite webcams, current entrance wait times, and elevation-aware National Weather Service point forecasts for the Valley, the rim, and the high country, all on one page. Bookmark it and check it the morning you drive in."
    ) +
    `<p>For what the conditions mean for a plan, see <a href="/itineraries">the itineraries</a> and <a href="/planning">the Planning Guide</a>.</p>`,
  "/now": () => {
    // The current edition ships to non-JS crawlers as prose: this page's value
    // to search is its freshness, and bulletin.json is imported at deploy time
    // so every per-edition merge re-deploys the Worker with the new board.
    const ed = bulletin.edition || {};
    const parts = [
      hubProse(
        "The Park Bulletin",
        `Everything happening in Yosemite right now on one scannable page, condensed from the park's Yosemite Guide for ${ed.label || "the current edition"}: closures, roads, free ranger programs, dated events, trail status, hours, and phone numbers.`
      ),
    ];
    if (ed.lede) parts.push(`<p>${escapeHtmlText(ed.lede)}</p>`);
    if (Array.isArray(bulletin.alerts) && bulletin.alerts.length) {
      parts.push(
        `<h2>Changed this edition</h2><ul>${bulletin.alerts.map((a) => `<li>${escapeHtmlText(a)}</li>`).join("")}</ul>`
      );
    }
    if (Array.isArray(bulletin.areas) && bulletin.areas.length) {
      parts.push(
        `<h2>Roads and areas</h2><ul>${bulletin.areas
          .map((a) => `<li>${escapeHtmlText(a.name)} (${escapeHtmlText(a.chip)}): ${escapeHtmlText(a.note)}</li>`)
          .join("")}</ul>`
      );
    }
    if (Array.isArray(bulletin.valleyDay) && bulletin.valleyDay.length) {
      parts.push(
        `<h2>The Valley, by the clock</h2><ul>${bulletin.valleyDay
          .map((p) => `<li>${escapeHtmlText(p.time)}: ${escapeHtmlText(p.title)} (${escapeHtmlText(p.days)})</li>`)
          .join("")}</ul>`
      );
    }
    if (Array.isArray(bulletin.events) && bulletin.events.length) {
      parts.push(
        `<h2>On the calendar this edition</h2><ul>${bulletin.events
          .map((ev) => `<li>${escapeHtmlText(ev.dates)}: ${escapeHtmlText(ev.title)}, ${escapeHtmlText(ev.where)}</li>`)
          .join("")}</ul>`
      );
    }
    if (Array.isArray(bulletin.trails) && bulletin.trails.length) {
      parts.push(
        `<h2>Trails right now</h2><ul>${bulletin.trails
          .map((t) => `<li>${escapeHtmlText(t.name)} (${escapeHtmlText(t.chip)}): ${escapeHtmlText(t.note)}</li>`)
          .join("")}</ul>`
      );
    }
    parts.push(
      `<p>Live sources on <a href="/conditions">the conditions page</a>; the Sunday letter carries what changed on this board by email.</p>`
    );
    return parts.join("");
  },
  "/guide": () =>
    hubProse(
      "The Field Guide",
      "An offline web app for Yosemite: tappable GPS for the parking turnouts, quiet trailheads, and insider tactics that locals use, built to work at the trailhead when cell service dies. Includes the full stop library across the Valley, Glacier Point and Mariposa Grove, Tuolumne, and Hetch Hetchy, plus a day-by-day trip planner with park programs and weather."
    ) +
    `<p>The guide is on sale now: $19 once for 18 months of access, no subscription. The journal's free tools cover a lot on their own: <a href="/map">the trip planner map</a>, <a href="/itineraries">itineraries</a>, and <a href="/checklist">the first-week checklist</a>.</p>`,
  "/about": () =>
    hubProse(
      "About The Talus Field",
      "The Talus Field is an independent field journal of Yosemite National Park, written by Cory Goehring, a naturalist who lives in El Portal and has worked in and around the park for twenty seasons. Articles are checked on foot; gear is recommended only after real miles; nothing here is sponsored content."
    ),
  "/places": () =>
    hubProse(
      "The Directory",
      "A small, curated directory of Yosemite-area lodging, outfitters, guides, and tour operators, drawn from twenty seasons in and around the park. Listings are added slowly and on merit."
    ),
  "/newsletter": () =>
    hubProse(
      "Sunday Field Notes",
      "A short note on Yosemite most Sundays, when there is something to say: conditions, openings, what the park is doing right now. Subscribing also unlocks the interactive trip planner map. Free."
    ),
  "/contact": () =>
    hubProse(
      "Contact",
      "Send a note to the editor: trip questions, corrections, press, or anything else. Replies come from a real person in El Portal."
    ),
  "/advertise": () =>
    hubProse(
      "List your business",
      "How to list a Yosemite-area lodge, inn, guide service, or outfitter in The Talus Field directory, and what the listing includes."
    ),
  "/widget": () =>
    hubProse(
      "The Yosemite conditions widget",
      "A free embeddable box for Yosemite-area websites: live entrance waits from the National Park Service feed and the three-day Valley forecast from the National Weather Service, rendered by a single script tag with a credit link back to The Talus Field's conditions page. Built for gateway hotels, rental hosts, and tour operators."
    ) +
    `<p>See it live and copy the snippet on this page. The full conditions layer is at <a href="/conditions">/conditions</a>.</p>`,
  "/consult": () =>
    hubProse(
      "Field consult: thirty minutes on your Yosemite plan",
      "A one-on-one planning session with a naturalist who lives in Yosemite: dates, group, and constraints turned into a plan that fits the park as it will actually be that week. Thirty minutes by call, or the same session asynchronously as a written plan. A few slots a month; when they are gone, they are gone."
    ) +
    `<p>Most planning questions are answered free in <a href="/planning">the Planning Guide</a>, <a href="/itineraries">the itineraries</a>, and <a href="/map">the trip planner map</a>; the consult is for plans with real constraints.</p>`,
  "/firefall": () =>
    hubProse(
      "The Yosemite Firefall",
      "For roughly two weeks in mid-to-late February, sunset light can turn Horsetail Fall into a glowing orange ribbon on El Capitan. Three conditions must hold at once: water in the fall from recent rain or snowmelt, a clear western horizon at sunset, and the February sun angle. The glow builds for a few minutes, peaks near sunset, and is finished about ten minutes later."
    ) +
    `<p>The classic viewing zone is Northside Drive near the El Capitan Picnic Area; parking rules and any reservation requirement change annually, so check the NPS Horsetail Fall page before committing.</p>` +
    `<p>The full guide: <a href="/articles/horsetail-fall-firefall">the complete firefall article</a>. Live water and weather: <a href="/conditions">the conditions page</a>.</p>`,
};

// Shared-trip unfurls: /map?trip=id1,id2 links travel through texts and group
// chats, and the card is the click. Overrides title/description/og:image with
// the trip's stop count and first stop names (validated against the
// trip-points.json mirror; unknown ids are dropped, an all-invalid trip falls
// back to the generic /map card). `ogUrl` carries the full shared URL so
// scrapers unfurl the specific trip, while canonical stays a clean /map and
// search consolidates there. Cards are pre-generated by scripts/gen-og-cards.mjs.
const TRIP_OG_CARD_MAX = 20;
function applyTripSeo(seo, searchParams) {
  const trip = searchParams && searchParams.get("trip");
  if (!trip) return;
  const ids = [...new Set(trip.split(",").map((s) => s.trim()))].filter((id) =>
    Object.prototype.hasOwnProperty.call(tripPoints, id)
  );
  if (!ids.length) return;
  const n = ids.length;
  const names = ids.slice(0, 2).map((id) => tripPoints[id]);
  const rest = n - names.length;
  const stopList = rest > 0 ? `${names.join(", ")}, and ${rest} more` : names.join(", ");
  seo.title = `A ${n}-stop Yosemite trip — ${SITE_NAME}`;
  seo.description = `${stopList}, in drive order. A shared trip on the Talus Field planner map, curated by a resident of the park. Open it to see the route.`;
  seo.image = `${SITE_ORIGIN}/img/og/trip-${Math.min(n, TRIP_OG_CARD_MAX)}.jpg`;
  seo.ogUrl = `${SITE_ORIGIN}/map?trip=${ids.join(",")}`;
}

function seoForPath(pathname, searchParams) {
  const path = pathname.replace(/\/+$/, "") || "/";

  const articleMatch = path.match(/^\/articles\/([a-z0-9-]+)$/i);
  if (articleMatch) {
    const a = articles.find((x) => x.slug === articleMatch[1]);
    if (!a) return null;
    const cat = categories.find((c) => c.slug === a.cat);
    // Prefer the slug-named responsive variant (a few hundred KB, under the
    // social scrapers' size caps) over the multi-MB source JPEG.
    const image = absoluteImage(a.ogImage ? a.ogImage.url : a.image);
    const url = `${SITE_ORIGIN}/articles/${a.slug}`;
    // Prefer the short SEO description when authored, otherwise fall back to
    // the visible dek. Keeps Bing/Google snippets under the 160-char cutoff.
    const desc = a.seoDek || a.dek;
    return {
      title: `${a.title} — ${SITE_NAME}`,
      description: desc,
      canonical: url,
      ogType: "article",
      // Prerender hooks (see onRequest): the slug locates the committed
      // /prerender/<slug>.html prose fragment, the title heads the injected
      // block, and the hero path drives the per-route LCP preload (C12).
      prerenderSlug: a.slug,
      articleTitle: a.title,
      heroImagePath: a.image || null,
      image,
      imageWidth: a.ogImage ? a.ogImage.width : null,
      imageHeight: a.ogImage ? a.ogImage.height : null,
      imageAlt: a.placeholder || a.title,
      articleOg: {
        publishedTime: a.isoDate || null,
        modifiedTime: a.isoModified || a.isoDate || null,
        author: AUTHOR_NAME,
        section: cat ? cat.label : null,
      },
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "Article",
        headline: a.title,
        description: desc,
        image: [image],
        datePublished: a.isoDate || a.date,
        dateModified: a.isoModified || a.isoDate || a.date,
        articleSection: cat ? cat.label : undefined,
        wordCount: typeof a.wordCount === "number" ? a.wordCount : undefined,
        keywords: Array.isArray(a.keywords) && a.keywords.length ? a.keywords : undefined,
        author: { "@id": AUTHOR_ID },
        publisher: {
          "@type": "Organization",
          name: SITE_NAME,
          logo: { "@type": "ImageObject", url: PUBLISHER_LOGO },
        },
        mainEntityOfPage: { "@type": "WebPage", "@id": url },
        isAccessibleForFree: true,
        inLanguage: "en-US",
      },
      breadcrumb: breadcrumbLd([
        ["Home", `${SITE_ORIGIN}/`],
        cat ? [cat.label, `${SITE_ORIGIN}/section/${cat.slug}`] : null,
        [a.title, null],
      ].filter(Boolean)),
      faq: Array.isArray(a.faq) && a.faq.length ? faqLd(a.faq) : null,
      trail: a.trail ? trailLd(a, url) : null,
    };
  }

  const sectionMatch = path.match(/^\/section\/([a-z0-9-]+)$/i);
  if (sectionMatch) {
    const cat = categories.find((c) => c.slug === sectionMatch[1]);
    if (!cat) return null;
    const items = articles.filter((a) => a.cat === cat.slug);
    const url = `${SITE_ORIGIN}/section/${cat.slug}`;
    return {
      title: `${cat.label} — ${SITE_NAME}`,
      description: `${cat.blurb} ${items.length} entries from The Talus Field's Yosemite field journal.`,
      canonical: url,
      ogType: "website",
      image: SITE_DEFAULT_IMAGE,
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        name: `${cat.label} — ${SITE_NAME}`,
        description: cat.blurb,
        url,
        inLanguage: "en-US",
        isPartOf: { "@type": "WebSite", name: SITE_NAME, url: SITE_ORIGIN },
        hasPart: items.map((a) => ({
          "@type": "Article",
          headline: a.title,
          description: a.seoDek || a.dek,
          url: `${SITE_ORIGIN}/articles/${a.slug}`,
          datePublished: a.isoDate || a.date,
        })),
      },
      breadcrumb: breadcrumbLd([
        ["Home", `${SITE_ORIGIN}/`],
        [cat.label, null],
      ]),
      prose: hubProse(cat.label, `${cat.blurb} ${items.length} entries from The Talus Field's Yosemite field journal.`, articleLinkList(items)),
    };
  }

  const known = {
    "/": {
      title: `${SITE_NAME} — ${SITE_TAGLINE}`,
      description: SITE_DEFAULT_DESC,
    },
    "/articles": {
      title: `Articles — ${SITE_NAME}`,
      description:
        "Every entry, in reverse chronological order. Yosemite trip planning, trails, wildlife, and seasonal guides.",
      // CollectionPage whose mainEntity is the full catalog as an ItemList.
      // Mirrored client-side in app.jsx buildSeo so hydration replaces like
      // with like. Slim ListItems (url + name) avoid duplicating the Article
      // entities that live on the detail pages.
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        name: `Articles — ${SITE_NAME}`,
        url: `${SITE_ORIGIN}/articles`,
        description:
          "Every entry, in reverse chronological order. Yosemite trip planning, trails, wildlife, and seasonal guides.",
        inLanguage: "en-US",
        isPartOf: { "@type": "WebSite", name: SITE_NAME, url: SITE_ORIGIN },
        mainEntity: {
          "@type": "ItemList",
          numberOfItems: articles.length,
          itemListElement: articles.map((a, i) => ({
            "@type": "ListItem",
            position: i + 1,
            url: `${SITE_ORIGIN}/articles/${a.slug}`,
            name: a.title,
          })),
        },
      },
    },
    "/planning": {
      title: `The Yosemite Planning Guide — ${SITE_NAME}`,
      description:
        "Plan a Yosemite trip in 2026: entrances and getting there, gateway towns, permits, Half Dome, accessibility, smoke season, the seasonal calendar. A curated hub through The Talus Field's planning archive.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Planning Guide", null]],
      faq: [
        { q: "Do I need a reservation to enter Yosemite in 2026?", a: "No. The day-use vehicle reservation system is not in effect in 2026. A standard Yosemite entrance pass ($35 per vehicle, valid 7 days) is required." },
        { q: "What is the best time of year to visit Yosemite?", a: "Late May through early June for peak waterfalls and moderate crowds. September and October for warm days, smaller crowds, and golden light. July and August are the most crowded months. April has spring waterfalls but Tioga Road and Glacier Point Road are usually still closed." },
        { q: "How much does it cost to enter Yosemite?", a: "$35 per vehicle (7-day pass), $20 per person entering on foot or bike. Since January 1, 2026, international visitors pay a $100 per-person surcharge (age 16 and older). The America the Beautiful annual pass ($80 for U.S. residents, $250 for nonresidents) covers entry to all national parks for one year." },
        { q: "How long should I spend at Yosemite?", a: "Minimum two full days: one for the Valley floor, one for a second area like Glacier Point, Mariposa Grove, or Tioga Road. Three to four days lets you cover all of these without rushing. A single-day trip is doable but you'll be moving the entire time." },
        { q: "Is Yosemite open year-round?", a: "Yosemite Valley is open year-round. Tioga Road (Highway 120 through the park) is typically closed November through May. Glacier Point Road closes in late November and reopens around Memorial Day. Mariposa Grove is open year-round but the tram is seasonal. Some campgrounds have seasonal closures." }
      ],
    },
    "/checklist": {
      title: `The Yosemite First-Week Checklist — ${SITE_NAME}`,
      description:
        "A printable single-page checklist for planning a Yosemite trip in 2026: when to come, what to book, what to pack, gateway choice, and the non-negotiables. Free.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Planning Checklist", null]],
    },
    "/about": {
      title: `About — ${SITE_NAME}`,
      description:
        "About The Talus Field, an independent field journal of Yosemite kept by Cory Goehring, a resident of the park.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["About", null]],
    },
    "/kit": {
      title: `Kit — What I carry in Yosemite — ${SITE_NAME}`,
      description:
        "Gear lists for Yosemite: a day pack, an overnight pack, and a car kit. Each item with the reasoning behind it.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Kit", null]],
      // One ItemList per packing list. Matches the @graph app.jsx builds
      // client-side from window.KIT, so JS and non-JS crawlers see the same
      // entities. Sourced from the kit.json mirror.
      jsonLd: {
        "@context": "https://schema.org",
        "@graph": kit.lists.map((list) => ({
          "@type": "ItemList",
          name: list.title,
          description: list.summary,
          numberOfItems: list.items.length,
          itemListOrder: "https://schema.org/ItemListOrderAscending",
          url: `${SITE_ORIGIN}/kit#${list.slug}`,
          itemListElement: list.items.map((it, i) => ({
            "@type": "ListItem",
            position: i + 1,
            name: it.name,
            description: it.note,
          })),
        })),
      },
    },
    "/places": {
      title: `The Directory — Yosemite lodging and guides — ${SITE_NAME}`,
      description:
        "A small, curated directory of Yosemite-area lodging, outfitters, and guiding services, drawn from twenty seasons.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Directory", null]],
    },
    "/advertise": {
      title: `List your business — ${SITE_NAME}`,
      description:
        "How to list a Yosemite-area lodge, inn, guide service, or outfitter on The Talus Field directory.",
    },
    "/newsletter": {
      title: `Sunday Field Notes — ${SITE_NAME}`,
      description:
        "A short weekly note on Yosemite when there is something to say. Free.",
    },
    "/contact": {
      title: `Contact — ${SITE_NAME}`,
      description:
        "Send a note to the editor. Trip questions, corrections, press, or anything else.",
    },
    "/privacy": {
      title: `Privacy Policy — ${SITE_NAME}`,
      description:
        "What information The Talus Field collects, how it is used, and your rights under GDPR and CCPA.",
    },
    "/terms": {
      title: `Terms of Service — ${SITE_NAME}`,
      description:
        "Terms governing the use of The Talus Field, including content licensing and limitations of liability.",
    },
    "/affiliate": {
      title: `Affiliate Disclosure — ${SITE_NAME}`,
      description:
        "How affiliate links work on The Talus Field, and the editorial standards that don't change for paid placements.",
    },
    "/guide": {
      title: `The Field Guide — ${SITE_NAME}`,
      description:
        "An offline web app for Yosemite. Tappable GPS for the parking turnouts, quiet trailheads, and insider tactics that locals use. Works at the trailhead when service dies.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["The Field Guide", null]],
      // On sale since the July 2026 flip (GUIDE_ON_SALE in page-guide.jsx):
      // the page carries the live buy box.
    },
    "/films": {
      title: `Moving Pictures — the Yosemite Nature Notes film archive — ${SITE_NAME}`,
      description:
        "The complete Yosemite Nature Notes film series from the National Park Service, grouped by subject. Public domain, free to watch, most under ten minutes.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Films", null]],
      // ItemList of VideoObject nodes, one per episode, built from the
      // videos.json mirror. Matches the shape app.jsx builds client-side from
      // videos-data.js so JS and non-JS crawlers see the same entity.
      // uploadDate is deliberately omitted: only publication years are sourced.
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "ItemList",
        name: "Yosemite Nature Notes — the film archive",
        url: `${SITE_ORIGIN}/films`,
        numberOfItems: videos.length,
        itemListElement: videos.map((ep, i) => ({
          "@type": "VideoObject",
          position: i + 1,
          name: ep.title,
          description: ep.dek,
          thumbnailUrl: `https://i.ytimg.com/vi/${ep.youtubeId}/hqdefault.jpg`,
          embedUrl: `https://www.youtube-nocookie.com/embed/${ep.youtubeId}`,
          publisher: { "@type": "Organization", name: "National Park Service" },
          isAccessibleForFree: true,
        })),
      },
    },
    "/conditions": {
      title: `Yosemite Conditions — webcams, waits, and weather — ${SITE_NAME}`,
      description:
        "Live Yosemite webcams, entrance wait times, and elevation-aware weather forecasts on one page. Check it the morning you drive in.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Conditions", null]],
    },
    "/now": {
      title: `The Park Bulletin — what's happening in Yosemite right now — ${SITE_NAME}`,
      description:
        "Everything happening in Yosemite on one scannable page: closures, roads, free ranger programs, dated events, trail status, hours, and phone numbers, updated for each edition of the park's Yosemite Guide.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["The Park Bulletin", null]],
    },
    "/widget": {
      title: `Yosemite Conditions Widget — free embed for area businesses — ${SITE_NAME}`,
      description:
        "A free embeddable box with live Yosemite entrance waits and the three-day Valley forecast, for gateway hotels, rental hosts, and tour operators. One script tag.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Widget", null]],
    },
    "/consult": {
      title: `Field Consult — thirty minutes on your Yosemite plan — ${SITE_NAME}`,
      description:
        "A one-on-one planning consult with a Yosemite naturalist: your dates, group, and constraints, turned into a plan that fits the park. $95, thirty minutes, a few slots a month.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Field consult", null]],
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "Service",
        name: "Yosemite field consult",
        description:
          "A thirty-minute one-on-one Yosemite trip-planning consult with a resident naturalist, by call or as a written plan.",
        provider: { "@id": AUTHOR_ID },
        areaServed: { "@type": "Place", name: "Yosemite National Park" },
        url: `${SITE_ORIGIN}/consult`,
      },
    },
    "/firefall": {
      // Evergreen event page: no year in the URL or copy, so the same page
      // accrues rank every February instead of resetting on a dated slug.
      // FAQ answers come from the published article body
      // (bodies/horsetail-fall-firefall.jsx) per the no-invented-facts rule.
      title: `The Yosemite Firefall — dates, conditions, and how to plan — ${SITE_NAME}`,
      description:
        "When the Horsetail Fall firefall happens, the three conditions that must line up, and how to plan a February evening around uncertain odds. By a park resident.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Firefall", null]],
      faq: [
        {
          q: "When is the Yosemite firefall?",
          a: "The sun angle that lights Horsetail Fall runs roughly the second week of February through the last week, with the strongest color usually in the middle of that span. The glow builds for a few minutes, peaks near sunset, and is finished about ten minutes later.",
        },
        {
          q: "What has to happen for the firefall to appear?",
          a: "Three independent conditions must hold at once: water in Horsetail Fall from recent rain or snowmelt, a clear western horizon at sunset, and the mid-to-late-February sun angle. Any one failing cancels the show entirely.",
        },
        {
          q: "Where do you watch the firefall from?",
          a: "The classic viewing zone is Northside Drive near the El Capitan Picnic Area. Expect to park at a designated area, often Yosemite Falls parking, walk a mile or more each way, and be in place at least an hour before sunset.",
        },
        {
          q: "Do you need a reservation to see the firefall?",
          a: "In some years the park has required reservations for February weekends, along with parking restrictions and road closures. The rules change year to year; check the NPS Horsetail Fall page and current conditions in the week before your trip.",
        },
      ],
    },
    "/itineraries": {
      title: `Yosemite Itineraries — day plans on the map — ${SITE_NAME}`,
      description:
        "Curated Yosemite itineraries for one, two, or three days, plus a half-day plan for late arrivals. Each opens as a ready-made trip on the interactive map.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Itineraries", null]],
      // Built from ITINERARY_TRIPS below (hand-maintained mirror of
      // itineraries-data.js — this Worker imports JSON mirrors only). Matches
      // the ItemList app.jsx builds client-side; update ITINERARY_TRIPS when a
      // plan's title or dek changes there.
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "ItemList",
        name: "Yosemite itineraries",
        url: `${SITE_ORIGIN}/itineraries`,
        numberOfItems: ITINERARY_TRIPS.length,
        itemListElement: ITINERARY_TRIPS.map((t, i) => ({
          "@type": "ListItem",
          position: i + 1,
          item: {
            "@type": "TouristTrip",
            name: t.name,
            description: t.description,
            url: `${SITE_ORIGIN}/itineraries#${t.id}`,
            touristType: "National park visitors",
          },
        })),
      },
    },
    "/map": {
      title: `Yosemite Trip Planner Map — ${SITE_NAME}`,
      description:
        "An interactive Yosemite map of vistas, trailheads, parking turnouts, picnic spots, and places to eat, with a trip builder. Curated by a resident of the park. Free with an email signup.",
      breadcrumb: [["Home", `${SITE_ORIGIN}/`], ["Map", null]],
      // Honest, static WebPage node. The pin list itself stays out of the
      // structured data until the new points pass a ground-truth check.
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "WebPage",
        name: `Yosemite Trip Planner Map — ${SITE_NAME}`,
        url: `${SITE_ORIGIN}/map`,
        description:
          "An interactive Yosemite map of vistas, trailheads, parking turnouts, picnic spots, and places to eat, with a trip builder. Curated by a resident of the park. Free with an email signup.",
        isAccessibleForFree: true,
        inLanguage: "en-US",
        about: {
          "@type": "Place",
          name: "Yosemite National Park",
          geo: { "@type": "GeoCoordinates", latitude: 37.8651, longitude: -119.5383 },
        },
      },
    },
  };

  const meta = known[path];
  if (!meta) return null;
  const seo = {
    title: meta.title,
    description: meta.description,
    canonical: `${SITE_ORIGIN}${path === "/" ? "/" : path}`,
    ogType: "website",
    image: SITE_DEFAULT_IMAGE,
    jsonLd: meta.jsonLd || null,
    breadcrumb: meta.breadcrumb ? breadcrumbLd(meta.breadcrumb) : null,
    faq: meta.faq ? faqLd(meta.faq) : null,
    robots: meta.robots || null,
    prose: HUB_PROSE[path] ? HUB_PROSE[path]() : null,
  };
  if (path === "/map") applyTripSeo(seo, searchParams);
  return seo;
}

// Unmatched SPA routes (typos, dead slugs, removed pages) used to fall through
// to the 200 SPA fallback and index as thin homepage duplicates. Serve them as
// real 404s with noindex instead; app.jsx renders the matching not-found view.
function notFoundSeo(pathname) {
  return {
    title: `Page not found — ${SITE_NAME}`,
    description:
      "That page does not exist on The Talus Field. The articles index, planning guide, and trip planner map are good places to reorient.",
    canonical: `${SITE_ORIGIN}${pathname}`,
    ogType: "website",
    image: SITE_DEFAULT_IMAGE,
    jsonLd: null,
    breadcrumb: null,
    faq: null,
    robots: "noindex, follow",
    status: 404,
    prose:
      `<h1>Page not found</h1><p>There is nothing at this address. The link may be old, or the page may have moved.</p>` +
      `<p>Good places to reorient: <a href="/articles">the articles index</a>, <a href="/planning">the planning guide</a>, or <a href="/map">the trip planner map</a>.</p>`,
  };
}

// Mirror of slugifyImage in components.jsx / the gen scripts: derive the
// responsive variant basename from an image path.
function slugifyImagePath(image) {
  const base = String(image).split("/").pop() || "";
  return base.toLowerCase().replace(/\.[^.]+$/, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

// Per-route hero LCP preload (C12), mirroring index.html's home-hero preload:
// a responsive AVIF imagesrcset so the browser fetches the LCP image during HTML
// parse, ahead of React. Null for external/missing images.
function heroPreloadTag(imagePath) {
  if (!imagePath || /^https?:/i.test(imagePath)) return null;
  const cleaned = imagePath.replace(/^\/+/, "");
  const slash = cleaned.lastIndexOf("/");
  const dir = slash >= 0 ? cleaned.slice(0, slash) : "";
  const base = `/${dir ? dir + "/" : ""}responsive/${slugifyImagePath(cleaned)}`;
  const srcset = [400, 800, 1200, 1600].map((w) => `${base}-${w}.avif ${w}w`).join(", ");
  return `<link rel="preload" as="image" type="image/avif" imagesrcset="${srcset}" imagesizes="(max-width: 700px) 100vw, 700px" fetchpriority="high" />`;
}

function escapeHtmlText(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export default {
  fetch(request, env) {
    // The asset layer answers requests that match real files before the
    // Worker runs, so `next()` here is always the SPA-fallback index.html
    // (or a 404-shaped asset response) — the same thing Pages' context.next()
    // returned. Keeping the old handler shape makes the port a two-line diff.
    return handleRequest({ request, env, next: () => env.ASSETS.fetch(request) });
  },
};

// Named export for offline checks (scripts/, plain node): lets a test call the
// route metadata logic without workerd's HTMLRewriter runtime.
export { seoForPath };

// Permanent redirects, checked before any SEO work. The site had no redirect
// capability before the evergreen event pages landed (it is a Worker, not
// Pages, so there is no _redirects file); this table is the mechanism. Add an
// entry when a URL is retired or consolidated — e.g. if a year-stamped article
// slug ever folds into its evergreen event page — and crawlers get a real 301
// instead of a 404 or a duplicate.
const REDIRECTS = {
  // "/articles/some-retired-slug": "/firefall",
};

async function handleRequest({ request, next, env }) {
  const url = new URL(request.url);
  const redirectTarget = REDIRECTS[url.pathname.replace(/\/+$/, "") || "/"];
  if (redirectTarget) {
    return Response.redirect(`${SITE_ORIGIN}${redirectTarget}`, 301);
  }
  // Unknown SPA routes get a real 404 (with noindex + not-found prose) instead
  // of a 200 homepage clone. Real files never reach the Worker (asset-first
  // routing), so anything unmatched here is genuinely not a page.
  const seo = seoForPath(url.pathname, url.searchParams) || notFoundSeo(url.pathname);

  const response = await next();
  const ct = response.headers.get("content-type") || "";
  if (!ct.toLowerCase().includes("text/html")) return response;

  // Crawler-visible body text. Article routes fetch the committed prerendered
  // prose fragment (prefixed with the article <h1>); hub/section/not-found
  // routes carry their own fragment in seo.prose, <h1> included. Fails open:
  // any miss just leaves the SPA-only #root.
  let proseHtml = null;
  if (seo.prerenderSlug && env && env.ASSETS) {
    try {
      const pr = await env.ASSETS.fetch(new URL(`/prerender/${seo.prerenderSlug}.html`, url.origin));
      if (pr.ok) proseHtml = `<h1>${escapeHtmlText(seo.articleTitle || "")}</h1>` + (await pr.text());
    } catch (_e) { /* fail open: no injected prose */ }
  } else if (seo.prose) {
    proseHtml = seo.prose;
  }
  const heroPreload = seo.prerenderSlug ? heroPreloadTag(seo.heroImagePath) : null;
  // Route-aware static H1: the sr-only #seo-static-h1 in index.html carries the
  // homepage title for markup-only parsers. When a prose fragment is injected
  // it brings its own on-topic <h1>, so the static one is removed to avoid a
  // duplicate; otherwise it is rewritten to the route's title (site name
  // suffix stripped) so no route ships a topic-mismatched heading.
  const staticH1Text = proseHtml ? null : seo.title.replace(/\s+—\s+The Talus Field$/, "");

  const rewritten = new HTMLRewriter()
    .on("title", {
      element(el) {
        el.setInnerContent(seo.title);
      },
    })
    .on('meta[name="description"]', {
      element(el) {
        el.setAttribute("content", seo.description);
      },
    })
    .on('meta[name="twitter:title"]', {
      element(el) {
        el.setAttribute("content", seo.title);
      },
    })
    .on('meta[name="twitter:description"]', {
      element(el) {
        el.setAttribute("content", seo.description);
      },
    })
    .on('meta[name="twitter:image"]', {
      element(el) {
        el.setAttribute("content", seo.image);
      },
    })
    .on('meta[property="og:title"]', {
      element(el) {
        el.setAttribute("content", seo.title);
      },
    })
    .on('meta[property="og:description"]', {
      element(el) {
        el.setAttribute("content", seo.description);
      },
    })
    .on('meta[property="og:url"]', {
      element(el) {
        // Trip-share overrides set ogUrl to the full shared URL so scrapers
        // unfurl the specific trip; canonical stays the clean route.
        el.setAttribute("content", seo.ogUrl || seo.canonical);
      },
    })
    .on('meta[property="og:type"]', {
      element(el) {
        el.setAttribute("content", seo.ogType);
      },
    })
    .on('meta[property="og:image"]', {
      element(el) {
        el.setAttribute("content", seo.image);
      },
    })
    .on('meta[property="og:image:width"]', {
      element(el) {
        if (seo.imageWidth) el.setAttribute("content", String(seo.imageWidth));
      },
    })
    .on('meta[property="og:image:height"]', {
      element(el) {
        if (seo.imageHeight) el.setAttribute("content", String(seo.imageHeight));
      },
    })
    .on('link[rel="canonical"]', {
      element(el) {
        el.setAttribute("href", seo.canonical);
      },
    })
    .on('meta[name="robots"]', {
      element(el) {
        if (seo.robots) el.setAttribute("content", seo.robots);
      },
    })
    .on('meta[property="og:image:alt"]', {
      element(el) {
        if (seo.imageAlt) el.setAttribute("content", seo.imageAlt);
      },
    })
    .on("head", {
      element(el) {
        if (seo.articleOg) {
          const og = seo.articleOg;
          if (og.publishedTime) {
            el.append(
              `<meta property="article:published_time" content="${og.publishedTime}" />`,
              { html: true }
            );
          }
          if (og.modifiedTime) {
            el.append(
              `<meta property="article:modified_time" content="${og.modifiedTime}" />`,
              { html: true }
            );
          }
          if (og.author) {
            el.append(
              `<meta property="article:author" content="${og.author}" />`,
              { html: true }
            );
          }
          if (og.section) {
            el.append(
              `<meta property="article:section" content="${og.section}" />`,
              { html: true }
            );
          }
        }
        if (seo.jsonLd) {
          el.append(
            `<script type="application/ld+json" id="ld-page">${safeJsonForScript(seo.jsonLd)}</script>`,
            { html: true }
          );
        }
        if (seo.breadcrumb) {
          el.append(
            `<script type="application/ld+json" id="ld-breadcrumb">${safeJsonForScript(seo.breadcrumb)}</script>`,
            { html: true }
          );
        }
        if (seo.faq) {
          el.append(
            `<script type="application/ld+json" id="ld-faq">${safeJsonForScript(seo.faq)}</script>`,
            { html: true }
          );
        }
        if (seo.trail) {
          el.append(
            `<script type="application/ld+json" id="ld-trail">${safeJsonForScript(seo.trail)}</script>`,
            { html: true }
          );
        }
        if (heroPreload) {
          el.append(heroPreload, { html: true });
        }
      },
    })
    .on("#seo-static-h1", {
      element(el) {
        if (proseHtml) el.remove();
        else if (staticH1Text) el.setInnerContent(staticH1Text);
      },
    })
    .on("#root", {
      element(el) {
        // Inject the prose fragment (article body or hub summary, <h1>
        // included) as the first child of #root so non-JS crawlers see
        // route-specific text. The client boots with createRoot().render()
        // which replaces #root's children, and app.jsx also removes
        // #prerender-prose on boot, so JS users only ever see React's copy.
        if (proseHtml) {
          el.prepend(`<div id="prerender-prose">${proseHtml}</div>`, { html: true });
        }
      },
    })
    .transform(response);

  // Not-found routes ship the SPA shell (so the client can render its own
  // not-found view) but with a real 404 status for crawlers and link checkers.
  if (seo.status === 404) {
    return new Response(rewritten.body, {
      status: 404,
      statusText: "Not Found",
      headers: rewritten.headers,
    });
  }
  return rewritten;
}
