// GENERATED by scripts/gen-map-data.ts. Do not edit; rerun `npm run map:data`.
// The map's data files under public/, content-hashed: immutable, cached forever.

export const ROADS_URL = '/map/roads-21648485af.json'
export const ROADS_OSM_TIMESTAMP = '2026-09-27T21:11:12Z'
export const TRAILS_URL = '/map/trails-244d29aa6d.json'
