// GENERATED by scripts/gen-map-tiles.ts. Do not edit; rerun `npm run map:tiles`.
//
// The tile archives this build of the app reads. The version is a URL
// segment (/vt/<ver>/..., /dem/<ver>/...) and names the R2 objects, so both
// archives must be in the MAP_TILES bucket before this file ships.

export const TILESET = {
  version: "20260926-8a7bf247",
  basemapBuild: "20260926",
  basemap: { minzoom: 6, maxzoom: 15, attribution: "© <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors, <a href=\"https://protomaps.com\">Protomaps</a>" },
  dem: { minzoom: 6, maxzoom: 13, encoding: 'terrarium' as const, attribution: "Elevation: USGS 3DEP, SRTM, GMTED2010 via Mapzen Terrain Tiles" },
  bounds: [-120,37.42,-119,38.22] as [number, number, number, number],
  /** Tiles and stored bytes per offline pack, measured from the archives. */
  packs: {
    "overview": {
      "tiles": 150,
      "bytes": 5229919
    },
    "valley": {
      "tiles": 488,
      "bytes": 2911203
    },
    "glacier-wawona": {
      "tiles": 738,
      "bytes": 2902427
    },
    "tioga-tuolumne": {
      "tiles": 2038,
      "bytes": 9280184
    },
    "hetch-hetchy": {
      "tiles": 758,
      "bytes": 1951275
    }
  } as Record<string, { tiles: number; bytes: number }>,
}
